#!/bin/sh
# 
# Copyright (C) 2014 Neil McGill
#
# This game is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This game is distributed in the hope that it will be fun,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this game; if not, write to the Free
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ./scripts/common.sh

LOG=./build.log
MAINTAINER=goblinhack@gmail.com

tech_support()
{
    #
    # Record some useful to send back home on fail if we are permitted
    #
    (
        echo
        echo system install details
        echo ===================================================
        date
        apt --installed list | grep -i SDL
        apt --installed list | grep gcc
        apt --installed list | grep clang

        echo
        echo compilers
        echo ===================================================
        clang --version 
        gcc --version 
        uname -a 
    ) >> $LOG 2>&1
}

run() {
    ARGS=$1
    STDOUT=$2

    EXIT_CODE=.exit_code.$$
    ($1 2>&1; echo $? > $EXIT_CODE) | tee $STDOUT

    MY_RET=`cat $EXIT_CODE`

    return $MY_RET
}

run ./.RUNME $LOG

if [ $? -ne 0 ]; then

    log_err "Sorry for the screwup!"
    log_err "Enter 'y' if I can send $LOG to $MAINTAINER (who will be soundly whipped)?"
    read ans

    if [ "$ans" = "y" ]; then
        tech_support
        cat $LOG | mail -s "gorynlich build failed" $MAINTAINER
        if [ $? -ne 0 ]; then
            log_err "Rats. That failed too!"
            log_err "Ok. If you could send file $LOG manually to $MAINTAINER, would be appreciated."
        fi
    else
        log_err "Ok. If you could send file $LOG manually to $MAINTAINER, would be appreciated."
        log_err "Sorry for the screwup!"
    fi

    log "Thanks"
else
    if [ ! -f .built ]; then
        touch .built

        log "Built successfully. Would you mind if I send this build log to the $MAINTAINER"
        log "so I can keep track of what gcc version works? If not, no problem."
        log "Enter 'y' if this is ok"
        read ans

        if [ "$ans" = "y" ]; then
            tech_support
            cat $LOG | mail -s "gorynlich build passed" $MAINTAINER
        fi
    fi
fi
