/*
 * Copyright (C) 2011 Neil McGill
 *
 * See the README file.
 */

#include "tree.h"

void items_destroy(tree_rootp *);
void item_destroy(tree_rootp *, itemp i);
itemp item_find(tree_rootp, thingp);
itemp item_find_template(tree_rootp, thing_templatep);
itemp item_collect(tree_rootp *, thingp, thingp owner);
boolean item_drop(tree_rootp *, thingp);
const char *item_name(itemp i);
const char *item_shortname(itemp i);
thingp item_thing(itemp i);
itemp item_get_first(tree_rootp root);
itemp item_get_last(tree_rootp root);
itemp item_get_next(tree_rootp root, itemp item);
itemp item_get_prev(tree_rootp root, itemp item);
const char *item_logname(itemp);

boolean items_has_player(tree_rootp root);
boolean items_has_monst(tree_rootp root);
boolean items_has_snail(tree_rootp root);
boolean items_has_wall(tree_rootp root);
boolean items_has_star(tree_rootp root);
boolean items_has_rock(tree_rootp root);
boolean items_has_xxx2(tree_rootp root);
boolean items_has_xxx3(tree_rootp root);
boolean items_has_xxx4(tree_rootp root);
boolean items_has_xxx5(tree_rootp root);
boolean items_has_xxx6(tree_rootp root);
boolean items_has_xxx7(tree_rootp root);
boolean items_has_xxx8(tree_rootp root);
boolean items_has_is_star(tree_rootp root);
boolean items_has_powerup_spam(tree_rootp root);
boolean items_has_rock_0(tree_rootp root);
boolean items_has_car(tree_rootp root);
boolean items_has_star_green(tree_rootp root);
boolean items_has_star_cyan(tree_rootp root);
boolean items_has_star_black(tree_rootp root);
boolean items_has_star_purple(tree_rootp root);
boolean items_has_explosion(tree_rootp root);
boolean items_has_spikes(tree_rootp root);
boolean items_has_is_star_red(tree_rootp root);
boolean items_has_is_star_pink(tree_rootp root);
boolean items_has_is_star_blue(tree_rootp root);
boolean items_has_seedpod(tree_rootp root);
boolean items_has_bomb(tree_rootp root);
boolean items_has_spam(tree_rootp root);
boolean items_has_road(tree_rootp root);
boolean items_has_pipe(tree_rootp root);
boolean items_has_xxx27(tree_rootp root);
boolean items_has_xxx28(tree_rootp root);
boolean items_has_is_shrunk_when_carried(tree_rootp root);
boolean items_has_hidden_from_editor(tree_rootp root);
boolean items_has_rocket(tree_rootp root);
boolean items_has_is_left_as_corpse_on_death(tree_rootp root);
boolean items_has_item_perma(tree_rootp root);
boolean items_has_esnail(tree_rootp root);
boolean items_has_is_item_hidden(tree_rootp root);
boolean items_has_bonus_letter(tree_rootp root);
boolean items_has_is_thing(tree_rootp root);
boolean items_has_plant(tree_rootp root);
boolean items_has_food(tree_rootp root);
boolean items_has_floor(tree_rootp root);
boolean items_has_exit(tree_rootp root);
boolean items_has_letter(tree_rootp root);

uint32_t items_count_is_thing_template(tree_rootp tree, thing_templatep);
uint32_t items_count_is_player(tree_rootp root);
uint32_t items_count_is_monst(tree_rootp root);
uint32_t items_count_is_snail(tree_rootp root);
uint32_t items_count_is_wall(tree_rootp root);
uint32_t items_count_is_star_yellow(tree_rootp root);
uint32_t items_count_is_rock(tree_rootp root);
uint32_t items_count_is_xxx2(tree_rootp root);
uint32_t items_count_is_xxx3(tree_rootp root);
uint32_t items_count_is_xxx4(tree_rootp root);
uint32_t items_count_is_xxx5(tree_rootp root);
uint32_t items_count_is_xxx6(tree_rootp root);
uint32_t items_count_is_xxx7(tree_rootp root);
uint32_t items_count_is_xxx8(tree_rootp root);
uint32_t items_count_is_star(tree_rootp root);
uint32_t items_count_is_powerup_spam(tree_rootp root);
uint32_t items_count_is_rock_0(tree_rootp root);
uint32_t items_count_is_car(tree_rootp root);
uint32_t items_count_is_star_green(tree_rootp root);
uint32_t items_count_is_star_cyan(tree_rootp root);
uint32_t items_count_is_star_black(tree_rootp root);
uint32_t items_count_is_star_purple(tree_rootp root);
uint32_t items_count_is_explosion(tree_rootp root);
uint32_t items_count_is_spikes(tree_rootp root);
uint32_t items_count_is_star_red(tree_rootp root);
uint32_t items_count_is_star_pink(tree_rootp root);
uint32_t items_count_is_star_blue(tree_rootp root);
uint32_t items_count_is_seedpod(tree_rootp root);
uint32_t items_count_is_bomb(tree_rootp root);
uint32_t items_count_is_spam(tree_rootp root);
uint32_t items_count_is_road(tree_rootp root);
uint32_t items_count_is_pipe(tree_rootp root);
uint32_t items_count_is_item_removed_at_level_end(tree_rootp root);
uint32_t items_count_is_scarable(tree_rootp root);
uint32_t items_count_is_shrunk_when_carried(tree_rootp root);
uint32_t items_count_is_hidden_from_editor(tree_rootp root);
uint32_t items_count_is_powerup_rocket(tree_rootp root);
uint32_t items_count_is_left_as_corpse_on_death(tree_rootp root);
uint32_t items_count_is_item_perma(tree_rootp root);
uint32_t items_count_is_esnail(tree_rootp root);
uint32_t items_count_is_item_is_hidden(tree_rootp root);
uint32_t items_count_is_bonus_letter(tree_rootp root);
uint32_t items_count_is_thing(tree_rootp root);
uint32_t items_count_is_plant(tree_rootp root);
uint32_t items_count_is_food(tree_rootp root);
uint32_t items_count_is_floor(tree_rootp root);
uint32_t items_count_is_exit(tree_rootp root);
uint32_t items_count_is_letter(tree_rootp root);

itemp items_first_is_player(tree_rootp root);
itemp items_first_is_monst(tree_rootp root);
itemp items_first_is_snail(tree_rootp root);
itemp items_first_is_wall(tree_rootp root);
itemp items_first_is_star_yellow(tree_rootp root);
itemp items_first_is_rock(tree_rootp root);
itemp items_first_is_xxx2(tree_rootp root);
itemp items_first_is_xxx3(tree_rootp root);
itemp items_first_is_xxx4(tree_rootp root);
itemp items_first_is_xxx5(tree_rootp root);
itemp items_first_is_xxx6(tree_rootp root);
itemp items_first_is_xxx7(tree_rootp root);
itemp items_first_is_xxx8(tree_rootp root);
itemp items_first_is_star(tree_rootp root);
itemp items_first_is_powerup_spam(tree_rootp root);
itemp items_first_is_rock_0(tree_rootp root);
itemp items_first_is_car(tree_rootp root);
itemp items_first_is_star_green(tree_rootp root);
itemp items_first_is_star_cyan(tree_rootp root);
itemp items_first_is_star_black(tree_rootp root);
itemp items_first_is_star_purple(tree_rootp root);
itemp items_first_is_explosion(tree_rootp root);
itemp items_first_is_spikes(tree_rootp root);
itemp items_first_is_star_red(tree_rootp root);
itemp items_first_is_star_pink(tree_rootp root);
itemp items_first_is_star_blue(tree_rootp root);
itemp items_first_is_seedpod(tree_rootp root);
itemp items_first_is_bomb(tree_rootp root);
itemp items_first_is_spam(tree_rootp root);
itemp items_first_is_road(tree_rootp root);
itemp items_first_is_pipe(tree_rootp root);
itemp items_first_is_item_removed_at_level_end(tree_rootp root);
itemp items_first_is_scarable(tree_rootp root);
itemp items_first_is_shrunk_when_carried(tree_rootp root);
itemp items_first_is_hidden_from_editor(tree_rootp root);
itemp items_first_is_powerup_rocket(tree_rootp root);
itemp items_first_is_left_as_corpse_on_death(tree_rootp root);
itemp items_first_is_item_perma(tree_rootp root);
itemp items_first_is_esnail(tree_rootp root);
itemp items_first_is_item_is_hidden(tree_rootp root);
itemp items_first_is_bonus_letter(tree_rootp root);
itemp items_first_is_thing(tree_rootp root);
itemp items_first_is_plant(tree_rootp root);
itemp items_first_is_food(tree_rootp root);
itemp items_first_is_floor(tree_rootp root);
itemp items_first_is_exit(tree_rootp root);
itemp items_first_is_letter(tree_rootp root);

tree_rootp items_find_all_is_player(tree_rootp root);
tree_rootp items_find_all_is_monst(tree_rootp root);
tree_rootp items_find_all_is_snail(tree_rootp root);
tree_rootp items_find_all_is_wall(tree_rootp root);
tree_rootp items_find_all_is_star_yellow(tree_rootp root);
tree_rootp items_find_all_is_rock(tree_rootp root);
tree_rootp items_find_all_is_xxx2(tree_rootp root);
tree_rootp items_find_all_is_xxx3(tree_rootp root);
tree_rootp items_find_all_is_xxx4(tree_rootp root);
tree_rootp items_find_all_is_xxx5(tree_rootp root);
tree_rootp items_find_all_is_xxx6(tree_rootp root);
tree_rootp items_find_all_is_xxx7(tree_rootp root);
tree_rootp items_find_all_is_xxx8(tree_rootp root);
tree_rootp items_find_all_is_star(tree_rootp root);
tree_rootp items_find_all_is_powerup_spam(tree_rootp root);
tree_rootp items_find_all_is_rock_0(tree_rootp root);
tree_rootp items_find_all_is_car(tree_rootp root);
tree_rootp items_find_all_is_star_green(tree_rootp root);
tree_rootp items_find_all_is_star_cyan(tree_rootp root);
tree_rootp items_find_all_is_star_black(tree_rootp root);
tree_rootp items_find_all_is_star_purple(tree_rootp root);
tree_rootp items_find_all_is_explosion(tree_rootp root);
tree_rootp items_find_all_is_spikes(tree_rootp root);
tree_rootp items_find_all_is_star_red(tree_rootp root);
tree_rootp items_find_all_is_star_pink(tree_rootp root);
tree_rootp items_find_all_is_star_blue(tree_rootp root);
tree_rootp items_find_all_is_seedpod(tree_rootp root);
tree_rootp items_find_all_is_bomb(tree_rootp root);
tree_rootp items_find_all_is_spam(tree_rootp root);
tree_rootp items_find_all_is_road(tree_rootp root);
tree_rootp items_find_all_is_pipe(tree_rootp root);
tree_rootp items_find_all_is_item_removed_at_level_end(tree_rootp root);
tree_rootp items_find_all_is_scarable(tree_rootp root);
tree_rootp items_find_all_is_shrunk_when_carried(tree_rootp root);
tree_rootp items_find_all_is_hidden_from_editor(tree_rootp root);
tree_rootp items_find_all_is_powerup_rocket(tree_rootp root);
tree_rootp items_find_all_is_left_as_corpse_on_death(tree_rootp root);
tree_rootp items_find_all_is_item_perma(tree_rootp root);
tree_rootp items_find_all_is_esnail(tree_rootp root);
tree_rootp items_find_all_is_item_is_hidden(tree_rootp root);
tree_rootp items_find_all_is_bonus_letter(tree_rootp root);
tree_rootp items_find_all_is_thing(tree_rootp root);
tree_rootp items_find_all_is_plant(tree_rootp root);
tree_rootp items_find_all_is_food(tree_rootp root);
tree_rootp items_find_all_is_floor(tree_rootp root);
tree_rootp items_find_all_is_exit(tree_rootp root);
tree_rootp items_find_all_is_letter(tree_rootp root);

typedef struct tree_item_node_ {
    tree_key_pointer tree;
} tree_item_node;
