/*
 * Copyright (C) 2011 Neil McGill
 *
 * See the LICENSE file.
 */


boolean map_is_item_hidden_at(levelp, int32_t x, int32_t y);
boolean map_is_thing_at(levelp, int32_t x, int32_t y);
boolean map_is_bonus_letter_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx11_at(levelp, int32_t x, int32_t y);
boolean map_is_esnail_at(levelp, int32_t x, int32_t y);
boolean map_is_exit_at(levelp, int32_t x, int32_t y);
boolean map_is_floor_at(levelp, int32_t x, int32_t y);
boolean map_is_food_at(levelp, int32_t x, int32_t y);
boolean map_is_letter_at(levelp, int32_t x, int32_t y);
boolean map_is_monst_at(levelp, int32_t x, int32_t y);
boolean map_is_item_perma_at(levelp, int32_t x, int32_t y);
boolean map_is_plant_at(levelp, int32_t x, int32_t y);
boolean map_is_player_at(levelp, int32_t x, int32_t y);
boolean map_is_snail_at(levelp, int32_t x, int32_t y);
boolean map_is_star_yellow_at(levelp, int32_t x, int32_t y);
boolean map_is_wall_at(levelp, int32_t x, int32_t y);
boolean map_is_animated_at(levelp, int32_t x, int32_t y);
boolean map_is_follows_owner_at(levelp, int32_t x, int32_t y);
boolean map_is_powerup_rocket_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx1_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx2_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx3_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx4_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx5_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx6_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx7_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx8_at(levelp, int32_t x, int32_t y);
boolean map_is_star_at(levelp, int32_t x, int32_t y);
boolean map_is_powerup_spam_at(levelp, int32_t x, int32_t y);
boolean map_is_xxx11_at(levelp, int32_t x, int32_t y);
boolean map_is_car_at(levelp, int32_t x, int32_t y);
boolean map_is_star_green_at(levelp, int32_t x, int32_t y);
boolean map_is_star_cyan_at(levelp, int32_t x, int32_t y);
boolean map_is_star_black_at(levelp, int32_t x, int32_t y);
boolean map_is_star_purple_at(levelp, int32_t x, int32_t y);
boolean map_is_explosion_at(levelp, int32_t x, int32_t y);
boolean map_is_spikes_at(levelp, int32_t x, int32_t y);
boolean map_is_star_red_at(levelp, int32_t x, int32_t y);
boolean map_is_star_red_at(levelp, int32_t x, int32_t y);
boolean map_is_star_blue_at(levelp, int32_t x, int32_t y);
boolean map_is_seedpod_at(levelp, int32_t x, int32_t y);
boolean map_is_bomb_at(levelp, int32_t x, int32_t y);
boolean map_is_spam_at(levelp, int32_t x, int32_t y);
boolean map_is_door_at(levelp, int32_t x, int32_t y);
boolean map_is_pipe_at(levelp, int32_t x, int32_t y);
boolean map_is_item_removed_at_level_end_at(levelp, int32_t x, int32_t y);
boolean map_is_scarable_at(levelp, int32_t x, int32_t y);
boolean map_is_shrunk_when_carried_at(levelp, int32_t x, int32_t y);
boolean map_is_hidden_from_editor_at(levelp, int32_t x, int32_t y);
boolean map_is_left_as_corpse_on_death_at(levelp, int32_t x, int32_t y);

thing_templatep map_find_bonus_letter_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx11_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_is_item_hidden_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_esnail_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_exit_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_floor_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_food_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_is_left_as_corpse_on_death_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_letter_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_monst_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_item_perma_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_plant_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_player_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_snail_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_spawns_thing_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_star_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_wall_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx1_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx2_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx3_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx4_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx5_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx6_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx7_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx8_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_is_star_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_powerup_spam_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx11_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_car_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_star_green_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_star_cyan_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_star_black_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_star_purple_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_explosion_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_spikes_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_is_star_red_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_is_star_red_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_is_star_blue_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_seedpod_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_bomb_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_spam_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_door_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_pipe_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx27_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_xxx28_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_is_shrunk_when_carried_at(levelp, int32_t x, int32_t y, widp *);
thing_templatep map_find_hidden_from_editor_at(levelp, int32_t x, int32_t y, widp *);

thingp map_thing_is_item_hidden_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_thing_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_bonus_letter_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_esnail_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_exit_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_floor_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_food_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_letter_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_monst_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_item_perma_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_plant_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_player_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_snail_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_yellow_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_wall_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_animated_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_follows_owner_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_powerup_rocket_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_left_as_corpse_on_death_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx1_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx2_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx3_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx4_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx5_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx6_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx7_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx8_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_powerup_spam_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_xxx11_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_car_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_green_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_cyan_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_black_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_purple_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_explosion_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_spikes_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_red_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_red_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_star_blue_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_seedpod_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_bomb_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_spam_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_door_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_pipe_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_item_removed_at_level_end_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_scarable_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_shrunk_when_carried_at(levelp, int32_t x, int32_t y);
thingp map_thing_is_hidden_from_editor_at(levelp, int32_t x, int32_t y);

tree_rootp map_all_things_is_item_hidden(levelp);
tree_rootp map_all_things_is_item_hidden_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_thing(levelp);
tree_rootp map_all_things_is_thing_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_bonus_letter(levelp);
tree_rootp map_all_things_is_bonus_letter_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_esnail(levelp);
tree_rootp map_all_things_is_esnail_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_exit(levelp);
tree_rootp map_all_things_is_exit_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_floor(levelp);
tree_rootp map_all_things_is_floor_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_food(levelp);
tree_rootp map_all_things_is_food_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_letter(levelp);
tree_rootp map_all_things_is_letter_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_monst(levelp);
tree_rootp map_all_things_is_monst_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_item_perma(levelp);
tree_rootp map_all_things_is_item_perma_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_plant(levelp);
tree_rootp map_all_things_is_plant_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_player(levelp);
tree_rootp map_all_things_is_player_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_snail(levelp);
tree_rootp map_all_things_is_snail_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star_yellow(levelp);
tree_rootp map_all_things_is_star_yellow_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_wall(levelp);
tree_rootp map_all_things_is_wall_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx1(levelp);
tree_rootp map_all_things_is_animated(levelp);
tree_rootp map_all_things_is_animated_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_follows_owner(levelp);
tree_rootp map_all_things_is_follows_owner_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_powerup_rocket(levelp);
tree_rootp map_all_things_is_powerup_rocket_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx1_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx2(levelp);
tree_rootp map_all_things_is_xxx2_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx3(levelp);
tree_rootp map_all_things_is_xxx3_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx4(levelp);
tree_rootp map_all_things_is_xxx4_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx5(levelp);
tree_rootp map_all_things_is_xxx5_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx6(levelp);
tree_rootp map_all_things_is_xxx6_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx7(levelp);
tree_rootp map_all_things_is_xxx7_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx8(levelp);
tree_rootp map_all_things_is_xxx8_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star(levelp);
tree_rootp map_all_things_is_star_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_powerup_spam(levelp);
tree_rootp map_all_things_is_powerup_spam_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_xxx11(levelp);
tree_rootp map_all_things_is_xxx11_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_car(levelp);
tree_rootp map_all_things_is_car_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star_green(levelp);
tree_rootp map_all_things_is_star_green_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star_cyan(levelp);
tree_rootp map_all_things_is_star_cyan_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star_black(levelp);
tree_rootp map_all_things_is_star_black_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star_purple(levelp);
tree_rootp map_all_things_is_star_purple_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_explosion(levelp);
tree_rootp map_all_things_is_explosion_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_spikes(levelp);
tree_rootp map_all_things_is_spikes_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star_red(levelp);
tree_rootp map_all_things_is_star_red_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star_red(levelp);
tree_rootp map_all_things_is_star_red_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_star_blue(levelp);
tree_rootp map_all_things_is_star_blue_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_seedpod(levelp);
tree_rootp map_all_things_is_seedpod_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_bomb(levelp);
tree_rootp map_all_things_is_bomb_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_spam(levelp);
tree_rootp map_all_things_is_spam_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_door(levelp);
tree_rootp map_all_things_is_door_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_pipe(levelp);
tree_rootp map_all_things_is_pipe_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_item_removed_at_level_end(levelp);
tree_rootp map_all_things_is_item_removed_at_level_end_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_scarable(levelp);
tree_rootp map_all_things_is_scarable_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_shrunk_when_carried(levelp);
tree_rootp map_all_things_is_shrunk_when_carried_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_hidden_from_editor(levelp);
tree_rootp map_all_things_is_hidden_from_editor_at(levelp, int32_t x, int32_t y);
tree_rootp map_all_things_is_left_as_corpse_on_death(levelp);
tree_rootp map_all_things_is_left_as_corpse_on_death_at(levelp, int32_t x, int32_t y);

uint32_t level_count_is_item_is_hidden(levelp);
uint32_t level_count_is_thing(levelp);
uint32_t level_count_is_bonus_letter(levelp);
uint32_t level_count_is_esnail(levelp);
uint32_t level_count_is_exit(levelp);
uint32_t level_count_is_floor(levelp);
uint32_t level_count_is_food(levelp);
uint32_t level_count_is_letter(levelp);
uint32_t level_count_is_monst(levelp);
uint32_t level_count_is_item_perma(levelp);
uint32_t level_count_is_plant(levelp);
uint32_t level_count_is_player(levelp);
uint32_t level_count_is_snail(levelp);
uint32_t level_count_is_star_yellow(levelp);
uint32_t level_count_is_wall(levelp);
uint32_t level_count_is_follows_owner(levelp);
uint32_t level_count_is_powerup_rocket(levelp);
uint32_t level_count_is_xxx1(levelp);
uint32_t level_count_is_xxx2(levelp);
uint32_t level_count_is_xxx3(levelp);
uint32_t level_count_is_xxx4(levelp);
uint32_t level_count_is_xxx5(levelp);
uint32_t level_count_is_xxx6(levelp);
uint32_t level_count_is_xxx7(levelp);
uint32_t level_count_is_xxx8(levelp);
uint32_t level_count_is_star(levelp);
uint32_t level_count_is_powerup_spam(levelp);
uint32_t level_count_is_xxx11(levelp);
uint32_t level_count_is_car(levelp);
uint32_t level_count_is_star_green(levelp);
uint32_t level_count_is_star_cyan(levelp);
uint32_t level_count_is_star_black(levelp);
uint32_t level_count_is_star_purple(levelp);
uint32_t level_count_is_explosion(levelp);
uint32_t level_count_is_spikes(levelp);
uint32_t level_count_is_star_red(levelp);
uint32_t level_count_is_star_red(levelp);
uint32_t level_count_is_star_blue(levelp);
uint32_t level_count_is_seedpod(levelp);
uint32_t level_count_is_bomb(levelp);
uint32_t level_count_is_spam(levelp);
uint32_t level_count_is_door(levelp);
uint32_t level_count_is_pipe(levelp);
uint32_t level_count_is_item_removed_at_level_end(levelp);
uint32_t level_count_is_scarable(levelp);
uint32_t level_count_is_shrunk_when_carried(levelp);
uint32_t level_count_is_hidden_from_editor(levelp);
uint32_t level_count_is_left_as_corpse_on_death(levelp);

#include "tree.h"

typedef struct tree_thing_node_ {
    tree_key_pointer tree;
} tree_thing_node;

void map_fixup(levelp);
