/*
 * Copyright (C) 2011-2015 goblinhack@gmail.com
 *
 * See the LICENSE file for license.
 */

#include <SDL.h>
#include <string.h>

#include "main.h"
#include "name.h"

static const char *classes[] = {
    "warrior",
    "dwarf",
    "valkyrie",
    "elf",
    "wizard",
};

int pclass_count (void)
{
    return (ARRAY_SIZE(classes));
}

const char *pclass_random (void)
{
    return (classes[myrand() % ARRAY_SIZE(classes)]);
}

const char *pclass_nth (const int n)
{
    if (n >= ARRAY_SIZE(classes)) {
        return (0);
    }

    return (classes[n]);
}

int pclass_find (const char *pclass)
{
    if (!pclass) {
        return (-1);
    }

    int n;
    for (n = 0; n < ARRAY_SIZE(classes); n++) {
        if (!strcasecmp(pclass, classes[n])) {
            return (n);
        }
    }

    return (-1);
}

const char *name_random (const char *pclass)
{
    if (!strcasecmp(pclass, "wizard")) {
        static const char *names[] = {
            "Leynilegur",
            "Azazel",
            "Charon",
            "Myrkur",
            "Morke",
            "Mr reaper",
            "Abaddon",
            "Ad-dajal",
            "Agramon",
            "Belphegor",
            "Dajal",
            "Jouvart",
            "Mammon",
            "Olizer",
            "Memnoch",
            "Dajal",
            "Gressil",
            "Hellan",
            "Naberius",
            "Phenex",
            "Sallos",
            "Seere",
            "Stolas",
            "Surgat",
            "Verrin",
            "Vize",
            "Focalor",
            "Hagenti",
            "Ipos",
            "Asmodai",
            "Botis",
            "Bune",
            "Sabnock",
            "Berith",
            "Abdabadbab",
            "Al-dun-gone",
            "Hagglety",
            "Ilikalan",
            "Kadda",
            "Moonmaster",
            "Y-rggy-ish",
            "Yin'alashaga",
            "Zagazz",
            "Zarazagat",
            "Ziz",
        };

        return (names[myrand() % ARRAY_SIZE(names)]);
    } else if (!strcasecmp(pclass, "warrior")) {
        static const char *names[] = {
            "Ser Applespice",
            "Ser Ben",
            "Ser Bob",
            "Ser Doublebob",
            "Ser Benalot",
            "Ser Blackeye",
            "Ser Blackguard",
            "Ser Blackshield",
            "Ser Blackstone",
            "Ser Bloodbath",
            "Ser Bloodstone",
            "Ser Capitate",
            "Ser Castlecrusher",
            "Ser Daggerthief",
            "Ser Darkeye",
            "Ser Darkwing",
            "Ser Deathwatch",
            "Ser Draco",
            "Ser Dragonfire",
            "Ser Dragontail",
            "Ser Dragontooth",
            "Ser Drybones",
            "Ser Fleetfoot",
            "Ser Frossleberry",
            "Ser Gore",
            "Ser Gothicon",
            "Ser Graves",
            "Ser Green",
            "Ser Greenshield",
            "Ser Grimoire",
            "Ser Hamster",
            "Ser Hammerstone",
            "Ser Hemlock",
            "Ser Hooknose",
            "Ser John",
            "Ser Killsalot",
            "Ser Lancelion",
            "Ser Lash",
            "Ser Leggless",
            "Ser Lifstealer",
            "Ser Neilly",
            "Ser Richard",
            "Ser Percy",
            "Ser Purpleshield",
            "Ser Quincy",
            "Ser Redaxe",
            "Ser Richard",
            "Ser Sleek",
            "Ser Slink",
            "Ser Sly",
            "Ser Spanksalot",
            "Ser Stoker",
            "Ser Stuart",
            "Ser Swordheart",
            "Ser Tepid",
            "Ser Whipsalot",
            "Ser White",
            "Ser Whiteblade",
            "Ser Widowmaker",
            "Ser Winsalot",
            "Siyag",
            "Siyahl",
            "Skug",
            "Sting",
        };

        return (names[myrand() % ARRAY_SIZE(names)]);
    } else if (!strcasecmp(pclass, "elf")) {
        static const char *names[] = {
            "Yeldarb, Deathbringer",
            "Elgal",
            "Gaysprig",
            "Alandiel",
            "Lymbal",
            "Arielen",
            "Valien",
            "Siyag",
            "Siyahl",
            "Pyleva",
            "Lightfoot",
            "Windwalker",
            "Forestghost",
            "Everstar",
            "Erendhart",
            "Grynoille",
            "Numai",
            "Numenor",
            "Sadek",
            "Abucoeh",
            "Gleamdancer",
            "Aderanuel",
            "Greatsailor",
            "Adunlesd",
            "Spellcutter",
            "Agbaon",
            "Coldbear",
            "Ahareag",
            "Breezefang",
            "Alilaherg",
            "Dragoncarver",
            "Ananiab",
            "Flailwanderer",
            "Anenoer",
            "Blackseed",
            "Aniptolg",
            "Dancefletcher",
            "Asusihaag",
            "Sandtear",
            "Atanolr",
            "Magefletcher",
            "Atdats",
            "Swordbear",
            "Aterorc",
            "Darkbull",
            "Attier",
            "Lakeseeker",
            "Bedlunl",
            "Lyretraveller",
            "Buneas",
            "Cuthand",
            "Dapreut",
            "Branchwhip",
            "Dennaal",
            "Earthhunter",
            "Denoab",
            "Dragonseeker",
            "Derendaul",
            "Divesailor",
            "Dibpehl",
            "Greencutter",
            "Dorapn",
            "Dreampaw",
            "Dulseah",
            "Cloudstar",
            "Ebiracl",
            "Earthpath",
            "Ebneht",
            "Glitterflute",
            "Ecosigart",
            "Silenttail",
            "Ehanegaeb",
            "Dunejester",
            "Ehtair",
            "Nightbird",
            "Elaletand",
            "Lowtracker",
            "Elonhean",
            "Bearrider",
            "Enubdanl",
            "Shadepanther",
            "Epobunanr",
            "Lutefollower",
            "Erigbatd",
            "Shadejester",
            "Erohibt",
            "Magevictor",
            "Etaloag",
            "Shadowflail",
            "Gadrars",
            "Nightstar",
            "Gadredr",
            "Firebat",
            "Galanult",
            "Glowlock",
            "Galibs",
            "Duskgrass",
            "Hanhesh",
            "Archerseeker",
            "Herroll",
            "Dunetracker",
            "Hogiib",
            "Woodclaw",
            "Hogoac",
            "Bladepanther",
            "Ibrual",
            "Smilebird",
            "Icuheul",
            "Phoenixpacer",
            "Igerlaub",
            "Happybranch",
            "Ihubacn",
            "Snakestealer",
            "Ilanagh",
            "Buckjuggler",
            "Isotahair",
            "Battlebrewer",
            "Labarean",
            "Silentshooter",
            "Laduad",
            "Starwarrior",
            "Lahabaan",
            "Branchlizard",
            "Lotais",
            "Holybreaker",
            "Ludagn",
            "Starsting",
            "Nagacedb",
            "Pathboar",
            "Nalicl",
            "Sundusk",
            "Nastaag",
            "Branchwanderer",
            "Nasuhhaoh",
            "Featherhunter",
            "Nehharl",
            "Reddragon",
            "Notneah",
            "Brushpaw",
            "Nuhlial",
            "Daysinger",
            "Nunhald",
            "Scribeslayer",
            "Ogadaud",
            "Eyemaster",
            "Ohidideon",
            "Batvoyager",
            "Oladoal",
            "Chillbat",
            "Onilooh",
            "Archerseeker",
            "Otaneih",
            "Woodseeker",
            "Rashiar",
            "Prayerhare",
            "Reladauc",
            "Beakcarver",
            "Relagoil",
            "Holyhorse",
            "Taccuah",
            "Breezearcher",
            "Toballiol",
            "Dancemage",
            "Udorehl",
            "Fighterwanderer",
            "Upathill",
            "Skysong",
            "Uradein",
            "Hopebuck",
            "Adekur",
            "Adoder",
            "Amlid",
            "Anariz",
            "Aneeh",
            "Aneyise",
            "Anios",
            "Anrod",
            "Arazik",
            "Arovidet",
            "Arraz",
            "Asiic",
            "Atufeve",
            "Avrax",
            "Baxre",
            "Bunatixi",
            "Dinahmek",
            "Doselroz",
            "Ekael",
            "Erisar",
            "Errer",
            "Esiid",
            "Etrad",
            "Fokudani",
            "Hitac",
            "Honidiox",
            "Hulva",
            "Humenxis",
            "Idivunik",
            "Ikosorez",
            "Inariru",
            "Ireed",
            "Itoni",
            "Kama",
            "Karalal",
            "Katorrim",
            "Keranoc",
            "Kivef",
            "Lahabixi",
            "Laryflaz",
            "Lokis",
            "Nahoreik",
            "Nine",
            "Odayr",
            "Ofnah",
            "Raxurlyh",
            "Retu",
            "Rinyraef",
            "Rirha",
            "Ritozaek",
            "Ruhorrin",
            "Rumtu",
            "Rykilvob",
            "Seladeov",
            "Sibufrix",
            "Siror",
            "Sorahrad",
            "Sorartam",
            "Syrinaod",
            "Tava",
            "Ticaf",
            "Tonid",
            "Toxse",
            "Uretenu",
            "Urlof",
            "Uroet",
            "Uyihit",
            "Vadat",
            "Vaxod",
            "Xavav",
            "Xavek",
            "Xerytana",
            "Yezarim",
            "Ykabeli",
            "Elvis",
        };

        return (names[myrand() % ARRAY_SIZE(names)]);
    } else if (!strcasecmp(pclass, "dwarf")) {
        static const char *names[] = {
            "Aderanuel",
            "Greatsailor",
            "Adunlesd",
            "Spellcutter",
            "Agbaon",
            "Coldbear",
            "Ahareag",
            "Breezefang",
            "Alilaherg",
            "Dragoncarver",
            "Ananiab",
            "Flailwanderer",
            "Anenoer",
            "Blackseed",
            "Aniptolg",
            "Dancefletcher",
            "Asusihaag",
            "Sandtear",
            "Atanolr",
            "Magefletcher",
            "Atdats",
            "Swordbear",
            "Aterorc",
            "Darkbull",
            "Attier",
            "Lakeseeker",
            "Badgold",
            "Battlebreaker",
            "Badgold",
            "Battlebreaker",
            "Battlesmasher",
            "Beamender",
            "Beamsmasher",
            "Bladechop",
            "Bloodcrusher",
            "Bloodhill",
            "Bloodkiller",
            "Bloodmine",
            "Bravepit",
            "Bravesmasher",
            "Bronzeender",
            "Cairntracker",
            "Clubsapper",
            "Crystalminer",
            "Crystalquarrier",
            "Darkcut",
            "Deepbullion",
            "Devilsmasher",
            "Doomfighter",
            "Doommountain",
            "Earthsmiter",
            "Edgemelter",
            "Elfender",
            "Fardigger",
            "Fateender",
            "Fatesmiter",
            "Ghoulsmasher",
            "Giantender",
            "Gianthunter",
            "Glittermace",
            "Godiron",
            "Grandbolt",
            "Grandslayer",
            "Grayfighter",
            "Greatslasher",
            "Grimbreaker",
            "Grimingot",
            "Hammerbeard",
            "Holybattler",
            "Holyfinder",
            "Holysmasher",
            "Honormelter",
            "Honorpriest",
            "Keyslasher",
            "Lightquarry",
            "Lodehunter",
            "Lodeshaman",
            "Lowhunter",
            "Lowworker",
            "Macecrusher",
            "Minefighter",
            "Mineslayer",
            "Monsterhunter",
            "Pickfighter",
            "Prayerquarry",
            "Propcrusher",
            "Proptracker",
            "Quartzcutter",
            "Quartzsmelter",
            "Rockgilder",
            "Rocklock",
            "Rocktracker",
            "Shalehunter",
            "Shalesmasher",
            "Steelbeard",
            "Steelsmith",
            "Stonebolt",
            "Trollsmiter",
            "Warmolder",
            "Witchbreaker",
            "Wraithkiller",
            "Wraithsmasher",
            "Beardwalker",
            "Digur",
            "Grubby",
            "Tegur",
            "Droopy",
            "Sleepy",
            "Grumpy",
            "Bentonite",
            "Goldman",
            "Granitefoot",
            "Halfbeard",
            "Minestalker",
            "Narroweyes",
            "Avonstar",
            "Axemaster",
            "Goblinhacker",
            "Hardshaft",
            "Mithrein",
            "Beren",
            "Bator",
            "Bolor",
            "Balrogcrusher",
            "Stront",
            "Dynadwarve",
            "Rockjaw",
            "Balin",
            "Balinor",
            "Agrinor",
            "Bob Fossil",
        };

        return (names[myrand() % ARRAY_SIZE(names)]);
    } else if (!strcasecmp(pclass, "valkyrie")) {
        static const char *names[] = {
            "Lady Applespice",
            "Lady Benalot",
            "Lady Blackeye",
            "Lady Blackguard",
            "Lady Blackshield",
            "Lady Blackstone",
            "Lady Bloodbath",
            "Lady Bloodstone",
            "Lady Capitate",
            "Lady Castlecrusher",
            "Lady Daggerthief",
            "Lady Darkeye",
            "Lady Darkwing",
            "Lady Deathwatch",
            "Lady Draco",
            "Lady Dragonfire",
            "Lady Dragontail",
            "Lady Dragontooth",
            "Lady Drybones",
            "Lady Fleetfoot",
            "Lady Frossleberry",
            "Lady Gore",
            "Lady Gothicon",
            "Lady Graves",
            "Lady Green",
            "Lady Greenshield",
            "Lady Grimoire",
            "Lady Hamster",
            "Lady Hammerstone",
            "Lady Hemlock",
            "Lady Hooknose",
            "Lady John",
            "Lady Killsalot",
            "Lady Kobold",
            "Lady Lancelion",
            "Lady Lash",
            "Lady Leggless",
            "Lady Lifstealer",
            "Lady Steve",
            "Lady Purpleshield",
            "Lady Quincy",
            "Lady Redaxe",
            "Lady Richard",
            "Lady Sleek",
            "Lady Slink",
            "Lady Sly",
            "Lady Stoker",
            "Lady Stuart",
            "Lady Swordheart",
            "Lady Tepid",
            "Lady Whipsalot",
            "Lady White",
            "Lady Whiteblade",
            "Lady Widowmaker",
            "Lady Winsalot",
            "Lady Alegna",
            "Elohim",
            "Malakh",
            "Mekatron",
            "Raphaelle",
            "Uriel",
            "Gabriel",
            "Sinuzanon",
            "Apesiel",
            "Lonzael",
            "Ssenos",
            "Labpael",
            "Banel",
            "Potnlet",
            "Suhiel",
            "Tasekobp",
            "Secanael",
            "Rokartenon",
            "Osahah",
            "Sesiel",
            "Leltsit",
            "Mesaheniel",
            "Resimon",
            "Skuras",
            "Atison",
            "Artrot",
            "Bipenahaxiel",
            "Asetal",
            "Sazirap",
            "Cetpiel",
            "Rneholah",
            "Artinoax",
            "Edaharon",
            "Hasamihiel",
            "Olhasoon",
            "Raal",
            "Oneesr",
            "Uson",
            "Ltamut",
            "Nohhiel",
            "Adpoit",
            "Urohbezas",
            "Umiash",
            "Llihat",
            "Petanael",
            "Sihehohon",
            "Nroamuzael",
            "Mriheh",
            "Asozsisor",
            "Apehasael",
            "Heroriastar",
            "Loszanlanon",
            "Osutahon",
            "Rararaezlop",
            "Emael",
            "Hidanatalael",
            "Matsiseah",
        };

        return (names[myrand() % ARRAY_SIZE(names)]);
    } else {
        return ("nameless");
    }
}
