/*
 * Copyright (C) 2011 Neil McGill
 *
 * See the LICENSE file for license.
 */

#include <SDL.h>
#include <string.h>

#include "main.h"
#include "name.h"

const char *name_random (const char *pclass)
{
    if (!strcmp(pclass, "wizard")) {
        static const char *names[] = {
            "leynilegur",
            "azazel",
            "charon",
            "myrkur",
            "morke",
            "the reaper",
            "abaddon",
            "ad-dajal",
            "agramon",
            "belphegor",
            "dajal",
            "jouvart",
            "mammon",
            "oliver",
            "memnoch",
            "dajal",
            "gressil",
            "helen",
            "naberius",
            "phenex",
            "sallos",
            "seere",
            "stolas",
            "surgat",
            "verrin",
            "vine",
            "judith",
            "lilith",
            "focalor",
            "hagenti",
            "ipos",
            "asmodai",
            "botis",
            "bune",
            "sabnock",
            "berith",
            "abdabadbab",
            "al-dun-gone",
            "hagglety",
            "ilikalan",
            "kadda",
            "moonmaster",
            "y-rggy-ish",
            "yin'alashaga",
            "zagazz",
            "zarazagat",
            "ziz",
        };

        return (names[rand() % ARRAY_SIZE(names)]);
    } else if (!strcmp(pclass, "warrior")) {
        static const char *names[] = {
            "ser applespice",
            "ser ben",
            "ser benalot",
            "ser blackeye",
            "ser blackguard",
            "ser blackshield",
            "ser blackstone",
            "ser bloodbath",
            "ser bloodstone",
            "ser capitate",
            "ser castlecrusher",
            "ser daggerthief",
            "ser darkeye",
            "ser darkwing",
            "ser deathwatch",
            "ser draco",
            "ser dragonfire",
            "ser dragontail",
            "ser dragontooth",
            "ser drybones",
            "ser fleetfoot",
            "ser frossleberry",
            "ser gore",
            "ser gothicon",
            "ser graves",
            "ser green",
            "ser greenshield",
            "ser grimoire",
            "ser ham'l'ster",
            "ser hammerstone",
            "ser hemlock",
            "ser hooknose",
            "ser john",
            "ser killsalot",
            "ser lancelion",
            "ser lash",
            "ser leggless",
            "ser lifstealer",
            "ser neilly",
            "ser percy",
            "ser purpleshield",
            "ser quincy",
            "ser redaxe",
            "ser richard",
            "ser sleek",
            "ser slink",
            "ser sly",
            "ser spanksalot",
            "ser stoker",
            "ser stuart",
            "ser swordheart",
            "ser tepid",
            "ser whipsalot",
            "ser white",
            "ser whiteblade",
            "ser widowmaker",
            "ser winsalot",
            "siyag",
            "siyahl",
            "skug",
        };

        return (names[rand() % ARRAY_SIZE(names)]);
    } else if (!strcmp(pclass, "elf")) {
        static const char *names[] = {
            "elgal",
            "gaysprig",
            "alandiel",
            "lymbal",
            "arielen",
            "valien",
            "siyag",
            "siyahl",
            "pyleva",
            "lightfoot",
            "windwalker",
            "forestghost",
            "everstar",
            "erendhart",
            "grynoille",
            "numai",
            "numenor",
            "sadek",
            "Abucoeh Gleamdancer",
            "Aderanuel Greatsailor",
            "Adunlesd Spellcutter",
            "Agbaon Coldbear",
            "Ahareag Breezefang",
            "Alilaherg Dragoncarver",
            "Ananiab Flailwanderer",
            "Anenoer Blackseed",
            "Aniptolg Dancefletcher",
            "Asusihaag Sandtear",
            "Atanolr Magefletcher",
            "Atdats Swordbear",
            "Aterorc Darkbull",
            "Attier Lakeseeker",
            "Bedlunl Lyretraveller",
            "Buneas Cuthand",
            "Dapreut Branchwhip",
            "Dennaal Earthhunter",
            "Denoab Dragonseeker",
            "Derendaul Divesailor",
            "Dibpehl Greencutter",
            "Dorapn Dreampaw",
            "Dulseah Cloudstar",
            "Ebiracl Earthpath",
            "Ebneht Glitterflute",
            "Ecosigart Silenttail",
            "Ehanegaeb Dunejester",
            "Ehtair Nightbird",
            "Elaletand Lowtracker",
            "Elonhean Bearrider",
            "Enubdanl Shadepanther",
            "Epobunanr Lutefollower",
            "Erigbatd Shadejester",
            "Erohibt Magevictor",
            "Etaloag Shadowflail",
            "Gadrars Nightstar",
            "Gadredr Firebat",
            "Galanult Glowlock",
            "Galibs Duskgrass",
            "Hanhesh Archerseeker",
            "Herroll Dunetracker",
            "Hogiib Woodclaw",
            "Hogoac Bladepanther",
            "Ibrual Smilebird",
            "Icuheul Phoenixpacer",
            "Igerlaub Happybranch",
            "Ihubacn Snakestealer",
            "Ilanagh Buckjuggler",
            "Isotahair Battlebrewer",
            "Labarean Silentshooter",
            "Laduad Starwarrior",
            "Lahabaan Branchlizard",
            "Lotais Holybreaker",
            "Ludagn Starsting",
            "Nagacedb Pathboar",
            "Nalicl Sundusk",
            "Nastaag Branchwanderer",
            "Nasuhhaoh Featherhunter",
            "Nehharl Reddragon",
            "Notneah Brushpaw",
            "Nuhlial Daysinger",
            "Nunhald Scribeslayer",
            "Ogadaud Eyemaster",
            "Ohidideon Batvoyager",
            "Oladoal Chillbat",
            "Onilooh Archerseeker",
            "Otaneih Woodseeker",
            "Rashiar Prayerhare",
            "Reladauc Beakcarver",
            "Relagoil Holyhorse",
            "Taccuah Breezearcher",
            "Toballiol Dancemage",
            "Udorehl Fighterwanderer",
            "Upathill Skysong",
            "Uradein Hopebuck",
            "Adekur",
            "Adoder",
            "Amlid",
            "Anariz",
            "Aneeh",
            "Aneyise",
            "Anios",
            "Anrod",
            "Arazik",
            "Arovidet",
            "Arraz",
            "Asiic",
            "Atufeve",
            "Avrax",
            "Baxre",
            "Bunatixi",
            "Dinahmek",
            "Doselroz",
            "Ekael",
            "Erisar",
            "Errer",
            "Esiid",
            "Etrad",
            "Fokudani",
            "Hitac",
            "Honidiox",
            "Hulva",
            "Humenxis",
            "Idivunik",
            "Ikosorez",
            "Inariru",
            "Ireed",
            "Itoni",
            "Kama",
            "Karalal",
            "Katorrim",
            "Keranoc",
            "Kivef",
            "Lahabixi",
            "Laryflaz",
            "Lokis",
            "Nahoreik",
            "Nine",
            "Odayr",
            "Ofnah",
            "Raxurlyh",
            "Retu",
            "Rinyraef",
            "Rirha",
            "Ritozaek",
            "Ruhorrin",
            "Rumtu",
            "Rykilvob",
            "Seladeov",
            "Sibufrix",
            "Siror",
            "Sorahrad",
            "Sorartam",
            "Syrinaod",
            "Tava",
            "Ticaf",
            "Tonid",
            "Toxse",
            "Uretenu",
            "Urlof",
            "Uroet",
            "Uyihit",
            "Vadat",
            "Vaxod",
            "Xavav",
            "Xavek",
            "Xerytana",
            "Yezarim",
            "Ykabeli",
        };

        return (names[rand() % ARRAY_SIZE(names)]);
    } else if (!strcmp(pclass, "dwarf")) {
        static const char *names[] = {
            "Aderanuel Greatsailor",
            "Adunlesd Spellcutter",
            "Agbaon Coldbear",
            "Ahareag Breezefang",
            "Alilaherg Dragoncarver",
            "Ananiab Flailwanderer",
            "Anenoer Blackseed",
            "Aniptolg Dancefletcher",
            "Asusihaag Sandtear",
            "Atanolr Magefletcher",
            "Atdats Swordbear",
            "Aterorc Darkbull",
            "Attier Lakeseeker",
            "Badgold",
            "Battlebreaker",
            "Badgold",
            "Battlebreaker",
            "Battlesmasher",
            "Beamender",
            "Beamsmasher",
            "Bladechop",
            "Bloodcrusher",
            "Bloodhill",
            "Bloodkiller",
            "Bloodmine",
            "Bravepit",
            "Bravesmasher",
            "Bronzeender",
            "Cairntracker",
            "Clubsapper",
            "Crystalminer",
            "Crystalquarrier",
            "Darkcut",
            "Deepbullion",
            "Devilsmasher",
            "Doomfighter",
            "Doommountain",
            "Earthsmiter",
            "Edgemelter",
            "Elfender",
            "Fardigger",
            "Fateender",
            "Fatesmiter",
            "Ghoulsmasher",
            "Giantender",
            "Gianthunter",
            "Glittermace",
            "Godiron",
            "Grandbolt",
            "Grandslayer",
            "Grayfighter",
            "Greatslasher",
            "Grimbreaker",
            "Grimingot",
            "Hammerbeard",
            "Holybattler",
            "Holyfinder",
            "Holysmasher",
            "Honormelter",
            "Honorpriest",
            "Keyslasher",
            "Lightquarry",
            "Lodehunter",
            "Lodeshaman",
            "Lowhunter",
            "Lowworker",
            "Macecrusher",
            "Minefighter",
            "Mineslayer",
            "Monsterhunter",
            "Pickfighter",
            "Prayerquarry",
            "Propcrusher",
            "Proptracker",
            "Quartzcutter",
            "Quartzsmelter",
            "Rockgilder",
            "Rocklock",
            "Rocktracker",
            "Shalehunter",
            "Shalesmasher",
            "Steelbeard",
            "Steelsmith",
            "Stonebolt",
            "Trollsmiter",
            "Warmolder",
            "Witchbreaker",
            "Wraithkiller",
            "Wraithsmasher",
            "beardwalker",
            "digur",
            "grubby",
            "tegur",
            "droopy",
            "sleepy",
            "grumpy",
            "bentonite",
            "goldman",
            "granitefoot",
            "halfbeard",
            "minestalker",
            "narroweyes",
            "avonstar",
            "axemaster",
            "goblinhacker",
            "hardshaft",
            "mithrein",
            "beren",
            "bator",
            "bolor",
            "balrogcrusher",
            "stront",
            "dynadwarve",
            "rockjaw",
            "balin",
            "balinor",
            "agrinor",
        };

        return (names[rand() % ARRAY_SIZE(names)]);
    } else if (!strcmp(pclass, "valkyrie")) {
        static const char *names[] = {
            "lady applespice",
            "lady boy",
            "lady benalot",
            "lady blackeye",
            "lady blackguard",
            "lady blackshield",
            "lady blackstone",
            "lady bloodbath",
            "lady bloodstone",
            "lady capitate",
            "lady castlecrusher",
            "lady daggerthief",
            "lady darkeye",
            "lady darkwing",
            "lady deathwatch",
            "lady draco",
            "lady dragonfire",
            "lady dragontail",
            "lady dragontooth",
            "lady drybones",
            "lady fleetfoot",
            "lady frossleberry",
            "lady gore",
            "lady gothicon",
            "lady graves",
            "lady green",
            "lady greenshield",
            "lady grimoire",
            "lady ham'l'ster",
            "lady hammerstone",
            "lady hemlock",
            "lady hooknose",
            "lady john",
            "lady killsalot",
            "lady lancelion",
            "lady lash",
            "lady leggless",
            "lady lifstealer",
            "lady steve",
            "lady purpleshield",
            "lady quincy",
            "lady redaxe",
            "lady richard",
            "lady sleek",
            "lady slink",
            "lady sly",
            "lady spanksalot",
            "lady stoker",
            "lady stuart",
            "lady swordheart",
            "lady tepid",
            "lady whipsalot",
            "lady white",
            "lady whiteblade",
            "lady widowmaker",
            "lady winsalot",
            "angela",
            "elohim",
            "malakh",
            "mekatron",
            "michaelle",
            "raphaelle",
            "uriel",
            "gabriel",
            "Sinuzanon",
            "Apesiel",
            "Lonzael",
            "Ssenos",
            "Labpael",
            "Banel",
            "Potnlet",
            "Suhiel",
            "Tasekobp",
            "Secanael",
            "Rokartenon",
            "Osahah",
            "Sesiel",
            "Leltsit",
            "Mesaheniel",
            "Resimon",
            "Skuras",
            "Atison",
            "Artrot",
            "Bipenahaxiel",
            "Asetal",
            "Sazirap",
            "Cetpiel",
            "Rneholah",
            "Artinoax",
            "Edaharon",
            "Hasamihiel",
            "Olhasoon",
            "Raal",
            "Oneesr",
            "Uson",
            "Ltamut",
            "Nohhiel",
            "Adpoit",
            "Urohbezas",
            "Umiash",
            "Llihat",
            "Petanael",
            "Sihehohon",
            "Nroamuzael",
            "Mriheh",
            "Asozsisor",
            "Apehasael",
            "Heroriastar",
            "Loszanlanon",
            "Osutahon",
            "Rararaezlop",
            "Emael",
            "Hidanatalael",
            "Matsiseah",
        };

        return (names[rand() % ARRAY_SIZE(names)]);
    } else {
        return ("nameless");
    }
}
