/*
 * Copyright (C) 2011 Neil McGill
 *
 * See the README file for license.
 */

#include <SDL.h>

#include "main.h"
#include "resource.h"
#include "tex.h"
#include "tile.h"
#include "init_fn.h"
#include "thing.h"

static uint8_t resource_init_1 (void *context)
{
    return (tex_load("data/gfx/gorynlich.png",
                     "gorynlich") != 0);
}

static uint8_t resource_init_2 (void *context)
{
    return (tex_load("data/gfx/title2.png",
                     "title2") != 0);
}

static uint8_t resource_init_3 (void *context)
{
    return (tex_load("data/gfx/title.png",
                     "title") != 0);
}

static uint8_t resource_init_4 (void *context)
{
    return (tex_load("data/gfx/help1.png",
                     "help1") != 0);
}

static uint8_t resource_init_5 (void *context)
{
    return (tex_load("data/gfx/help2.png",
                     "help2") != 0);
}

static uint8_t resource_init_6 (void *context)
{
    return (tex_load("data/gfx/help3.png",
                     "help3") != 0);
}

static uint8_t resource_init_7 (void *context)
{
    return (tex_load("data/gfx/dragon.png",
                     "dragon") != 0);
}

static uint8_t resource_init_8 (void *context)
{
    return (tex_load("data/gfx/title3.png",
                     "title3") != 0);
}

static uint8_t resource_init_9 (void *context)
{
    return (tex_load("data/gfx/title_small.png",
                     "title_small") != 0);
}

static uint8_t resource_init_10 (void *context)
{
    return (tex_load("data/gfx/gravestone.png",
                     "gravestone") != 0);
}

static uint8_t resource_init_11 (void *context)
{
    return (tex_load("data/gfx/gravestone2.png",
                     "gravestone2") != 0);
}

static uint8_t resource_init_12 (void *context)
{
    return (true);
}

static uint8_t resource_init_13 (void *context)
{
    return (tex_load_tiled("data/gfx/explosion.png",
                           "explosion",
                           1024, 1024) != 0);
}

static uint8_t resource_init_14 (void *context)
{
    return (tex_load_tiled("data/gfx/cloudkill.png",
                           "cloudkill",
                           1024, 1024) != 0);
}

static uint8_t resource_init_15 (void *context)
{
    return (tex_load_tiled("data/gfx/poison.png",
                           "poison",
                           1024, 1024) != 0);
}

static uint8_t resource_init_16 (void *context)
{
    return (true);
}

static uint8_t resource_init_17 (void *context)
{
    return (true);
}

static uint8_t resource_init_18 (void *context)
{
    return (true);
}

static uint8_t resource_init_19 (void *context)
{
    return (true);
}

static uint8_t resource_init_20 (void *context)
{
    return (true);
}

static uint8_t resource_init_21 (void *context)
{
    return (tex_load_tiled("data/gfx/sprites_small.png",
                           "sprites_small",
                           TILE_WIDTH, TILE_HEIGHT) != 0);
}

static uint8_t resource_init_22 (void *context)
{
    return (true);
}

static uint8_t resource_init_23 (void *context)
{
    static const char *small_tiles[] = {
        // --------------------------------------------------------------------
        "space",
        "large-collision-map",
        "medium-collision-map",
        "small-collision-map",
        "tiny-collision-map",
        "noentry",
        "apple_poison",
        "apple",
        "bread",
        "banana",
        "cheese",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "brazier1",
        "brazier2",
        "brazier3",
        "brazier4",
        "brazier5",
        "brazier6",
        // --------------------------------------------------------------------
        "key",
        "keys2",
        "keys3",
        "coins1",
        "chest1",
        "amulet1",
        "water",
        "water_poison",
        "spam",
        "potion_monsticide",
        "potion_fire",
        "potion_cloudkill",
        "potion_life",
        "potion_shield",
        "ring1",
        "ring2",
        "ring3",
        "gem1",
        "gem2",
        "gem3",
        "gem4",
        "gem5",
        "gem6",
        "gem7",
        "generator1",
        "bonepile3",
        "bonepile2",
        "bonepile1",
        "generator5",
        "generator6",
        "generator7",
        0,
        // --------------------------------------------------------------------
        "wand-fire1",
        "wand-fire2",
        "wand-fire3",
        "wand-fire4",
        "bow2",
        "bow3",
        "bow1",
        "bow4",
        "sphere1",
        "sphere2",
        "sphere3",
        "sphere4",
        "arrow-up",
        "arrow-tr",
        "arrow-right",
        "arrow-br",
        "arrow-down",
        "arrow-bl",
        "arrow-left",
        "arrow-tl",
        "tunnel1.1",
        "tunnel1.4",
        0,
        "exit2.1",
        "exit3.1",
        "exit4.1",
        "exit5.1",
        "exit6.1",
        "exit7.1",
        "exit1.1",
        0,
        0,
        // --------------------------------------------------------------------
        "sword1",
        "sword2",
        "sword3",
        "axe1",
        "axe2",
        "scythe1",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "tunnel1.2",
        "tunnel1.5",
        0,
        "exit2.2",
        "exit3.2",
        "exit4.2",
        "exit5.2",
        "exit6.2",
        "exit7.2",
        "exit1.2",
        0,
        0,
        // --------------------------------------------------------------------
        "floor1a",
        "floor1b",
        "floor1c",
        "floor1d",
        "floor1e",
        "floor1f",
        "floor1g",
        "floor1h",
        "floor2a",
        "floor2b",
        "floor2c",
        "floor2d",
        "floor2e",
        "floor2f",
        "floor2g",
        "floor2h",
        0,
        0,
        0,
        0,
        "tunnel1.3",
        "tunnel1.6",
        0,
        "exit2.3",
        "exit3.3",
        "exit4.3",
        "exit5.3",
        "exit6.3",
        "exit7.3",
        "exit1.3",
        0,
        0,
        // --------------------------------------------------------------------
        "plant1",
        "plant2",
        "plant3",
        "plant4",
        "plant5",
        "plant6",
        "plant7",
        "plant8",
        "plant9",
        "plant10",
        "plant11",
        "plant12",
        "seedpod1",
        "seedpod2",
        "seedpod3",
        "seedpod4",
        "seedpod5",
        "seedpod6",
        "seedpod7",
        "seedpod8",
        "seedpod9",
        "seedpod10",
        0,
        "exit2.4",
        "exit3.4",
        "exit4.4",
        "exit5.4",
        "exit6.4",
        "exit7.4",
        "exit1.4",
        0,
        0,
        // --------------------------------------------------------------------
        "floor3a",
        "floor3b",
        "floor3c",
        "floor3d",
        "floor3e",
        "floor3f",
        "floor3g",
        "floor3h",

        "floor4a",
        "floor4b",
        "floor4c",
        "floor4d",
        "floor4e",
        "floor4f",
        "floor4g",
        "floor4h",

        "floor5a",
        "floor5b",
        "floor5c",
        "floor5d",
        "floor5e",
        "floor5f",
        "floor5g",
        "floor5h",

        "floor6a",
        "floor6b",
        "floor6c",
        "floor6d",
        "floor6e",
        "floor6f",
        "floor6g",
        "floor6h",
        // --------------------------------------------------------------------
        "door_1_0",
        "door_1_is_join_node",
        "door_1_is_join_left",
        "door_1_is_join_bot",
        "door_1_is_join_right",
        "door_1_is_join_top",
        "door_1_is_join_horiz",
        "door_1_is_join_vert",
        "door_1_is_join_tl2",
        "door_1_is_join_bl2",
        "door_1_is_join_br2",
        "door_1_is_join_tr2",
        "door_1_is_join_tl",
        "door_1_is_join_bl",
        "door_1_is_join_br",
        "door_1_is_join_tr",
        "door_1_is_join_t270_3",
        "door_1_is_join_t180_3",
        "door_1_is_join_t90_3",
        "door_1_is_join_t_3",
        "door_1_is_join_t270",
        "door_1_is_join_t180",
        "door_1_is_join_t90",
        "door_1_is_join_t",
        "door_1_is_join_t270_2",
        "door_1_is_join_t180_2",
        "door_1_is_join_t90_2",
        "door_1_is_join_t_2",
        "door_1_is_join_t270_1",
        "door_1_is_join_t180_1",
        "door_1_is_join_t90_1",
        "door_1_is_join_t_1",
        // --------------------------------------------------------------------
        "door_1_is_join_x",
        "door_1_is_join_x1",
        "door_1_is_join_x1_270",
        "door_1_is_join_x1_180",
        "door_1_is_join_x1_90",
        "door_1_is_join_x2",
        "door_1_is_join_x2_270",
        "door_1_is_join_x2_180",
        "door_1_is_join_x2_90",
        "door_1_is_join_x3",
        "door_1_is_join_x3_180",
        "door_1_is_join_x4",
        "door_1_is_join_x4_270",
        "door_1_is_join_x4_180",
        "door_1_is_join_x4_90",
        "door_1_is_join_vert2",
        "door_1_is_join_horiz2",
        "pipe-bot",
        "pipe-left",
        "pipe-bl",
        "pipe-top",
        "pipe-vert",
        "pipe-tl",
        "pipe-t270",
        "pipe-right",
        "pipe-br",
        "pipe-horiz",
        "pipe-t180",
        "pipe-tr",
        "pipe-t90",
        "pipe-t",
        "pipe-x",
        // --------------------------------------------------------------------
        "door_2_0",
        "door_2_is_join_node",
        "door_2_is_join_left",
        "door_2_is_join_bot",
        "door_2_is_join_right",
        "door_2_is_join_top",
        "door_2_is_join_horiz",
        "door_2_is_join_vert",
        "door_2_is_join_tl2",
        "door_2_is_join_bl2",
        "door_2_is_join_br2",
        "door_2_is_join_tr2",
        "door_2_is_join_tl",
        "door_2_is_join_bl",
        "door_2_is_join_br",
        "door_2_is_join_tr",
        "door_2_is_join_t270_3",
        "door_2_is_join_t180_3",
        "door_2_is_join_t90_3",
        "door_2_is_join_t_3",
        "door_2_is_join_t270",
        "door_2_is_join_t180",
        "door_2_is_join_t90",
        "door_2_is_join_t",
        "door_2_is_join_t270_2",
        "door_2_is_join_t180_2",
        "door_2_is_join_t90_2",
        "door_2_is_join_t_2",
        "door_2_is_join_t270_1",
        "door_2_is_join_t180_1",
        "door_2_is_join_t90_1",
        "door_2_is_join_t_1",
        // --------------------------------------------------------------------
        "door_2_is_join_x",
        "door_2_is_join_x1",
        "door_2_is_join_x1_270",
        "door_2_is_join_x1_180",
        "door_2_is_join_x1_90",
        "door_2_is_join_x2",
        "door_2_is_join_x2_270",
        "door_2_is_join_x2_180",
        "door_2_is_join_x2_90",
        "door_2_is_join_x3",
        "door_2_is_join_x3_180",
        "door_2_is_join_x4",
        "door_2_is_join_x4_270",
        "door_2_is_join_x4_180",
        "door_2_is_join_x4_90",
        "door_2_is_join_vert2",
        "door_2_is_join_horiz2",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "wall1_0_0",
        "wall1_0_is_join_node",
        "wall1_0_is_join_left",
        "wall1_0_is_join_bot",
        "wall1_0_is_join_right",
        "wall1_0_is_join_top",
        "wall1_0_is_join_horiz",
        "wall1_0_is_join_vert",
        "wall1_0_is_join_tl2",
        "wall1_0_is_join_bl2",
        "wall1_0_is_join_br2",
        "wall1_0_is_join_tr2",
        "wall1_0_is_join_tl",
        "wall1_0_is_join_bl",
        "wall1_0_is_join_br",
        "wall1_0_is_join_tr",
        "wall1_0_is_join_t270_3",
        "wall1_0_is_join_t180_3",
        "wall1_0_is_join_t90_3",
        "wall1_0_is_join_t_3",
        "wall1_0_is_join_t270",
        "wall1_0_is_join_t180",
        "wall1_0_is_join_t90",
        "wall1_0_is_join_t",
        "wall1_0_is_join_t270_2",
        "wall1_0_is_join_t180_2",
        "wall1_0_is_join_t90_2",
        "wall1_0_is_join_t_2",
        "wall1_0_is_join_t270_1",
        "wall1_0_is_join_t180_1",
        "wall1_0_is_join_t90_1",
        "wall1_0_is_join_t_1",
        // --------------------------------------------------------------------
        "wall1_0_is_join_x",
        "wall1_0_is_join_x1",
        "wall1_0_is_join_x1_270",
        "wall1_0_is_join_x1_180",
        "wall1_0_is_join_x1_90",
        "wall1_0_is_join_x2",
        "wall1_0_is_join_x2_270",
        "wall1_0_is_join_x2_180",
        "wall1_0_is_join_x2_90",
        "wall1_0_is_join_x3",
        "wall1_0_is_join_x3_180",
        "wall1_0_is_join_x4",
        "wall1_0_is_join_x4_270",
        "wall1_0_is_join_x4_180",
        "wall1_0_is_join_x4_90",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "rock1_0_0",
        "rock1_0_is_join_node",
        "rock1_0_is_join_left",
        "rock1_0_is_join_bot",
        "rock1_0_is_join_right",
        "rock1_0_is_join_top",
        "rock1_0_is_join_horiz",
        "rock1_0_is_join_vert",
        "rock1_0_is_join_tl2",
        "rock1_0_is_join_bl2",
        "rock1_0_is_join_br2",
        "rock1_0_is_join_tr2",
        "rock1_0_is_join_tl",
        "rock1_0_is_join_bl",
        "rock1_0_is_join_br",
        "rock1_0_is_join_tr",
        "rock1_0_is_join_t270_3",
        "rock1_0_is_join_t180_3",
        "rock1_0_is_join_t90_3",
        "rock1_0_is_join_t_3",
        "rock1_0_is_join_t270",
        "rock1_0_is_join_t180",
        "rock1_0_is_join_t90",
        "rock1_0_is_join_t",
        "rock1_0_is_join_t270_2",
        "rock1_0_is_join_t180_2",
        "rock1_0_is_join_t90_2",
        "rock1_0_is_join_t_2",
        "rock1_0_is_join_t270_1",
        "rock1_0_is_join_t180_1",
        "rock1_0_is_join_t90_1",
        "rock1_0_is_join_t_1",
        // --------------------------------------------------------------------
        "rock1_0_is_join_x",
        "rock1_0_is_join_x1",
        "rock1_0_is_join_x1_270",
        "rock1_0_is_join_x1_180",
        "rock1_0_is_join_x1_90",
        "rock1_0_is_join_x2",
        "rock1_0_is_join_x2_270",
        "rock1_0_is_join_x2_180",
        "rock1_0_is_join_x2_90",
        "rock1_0_is_join_x3",
        "rock1_0_is_join_x3_180",
        "rock1_0_is_join_x4",
        "rock1_0_is_join_x4_270",
        "rock1_0_is_join_x4_180",
        "rock1_0_is_join_x4_90",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "wall2_0_0",
        "wall2_0_is_join_node",
        "wall2_0_is_join_left",
        "wall2_0_is_join_bot",
        "wall2_0_is_join_right",
        "wall2_0_is_join_top",
        "wall2_0_is_join_horiz",
        "wall2_0_is_join_vert",
        "wall2_0_is_join_tl2",
        "wall2_0_is_join_bl2",
        "wall2_0_is_join_br2",
        "wall2_0_is_join_tr2",
        "wall2_0_is_join_tl",
        "wall2_0_is_join_bl",
        "wall2_0_is_join_br",
        "wall2_0_is_join_tr",
        "wall2_0_is_join_t270_3",
        "wall2_0_is_join_t180_3",
        "wall2_0_is_join_t90_3",
        "wall2_0_is_join_t_3",
        "wall2_0_is_join_t270",
        "wall2_0_is_join_t180",
        "wall2_0_is_join_t90",
        "wall2_0_is_join_t",
        "wall2_0_is_join_t270_2",
        "wall2_0_is_join_t180_2",
        "wall2_0_is_join_t90_2",
        "wall2_0_is_join_t_2",
        "wall2_0_is_join_t270_1",
        "wall2_0_is_join_t180_1",
        "wall2_0_is_join_t90_1",
        "wall2_0_is_join_t_1",
        // --------------------------------------------------------------------
        "wall2_0_is_join_x",
        "wall2_0_is_join_x1",
        "wall2_0_is_join_x1_270",
        "wall2_0_is_join_x1_180",
        "wall2_0_is_join_x1_90",
        "wall2_0_is_join_x2",
        "wall2_0_is_join_x2_270",
        "wall2_0_is_join_x2_180",
        "wall2_0_is_join_x2_90",
        "wall2_0_is_join_x3",
        "wall2_0_is_join_x3_180",
        "wall2_0_is_join_x4",
        "wall2_0_is_join_x4_270",
        "wall2_0_is_join_x4_180",
        "wall2_0_is_join_x4_90",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "wall3_0_0",
        "wall3_0_is_join_node",
        "wall3_0_is_join_left",
        "wall3_0_is_join_bot",
        "wall3_0_is_join_right",
        "wall3_0_is_join_top",
        "wall3_0_is_join_horiz",
        "wall3_0_is_join_vert",
        "wall3_0_is_join_tl2",
        "wall3_0_is_join_bl2",
        "wall3_0_is_join_br2",
        "wall3_0_is_join_tr2",
        "wall3_0_is_join_tl",
        "wall3_0_is_join_bl",
        "wall3_0_is_join_br",
        "wall3_0_is_join_tr",
        "wall3_0_is_join_t270_3",
        "wall3_0_is_join_t180_3",
        "wall3_0_is_join_t90_3",
        "wall3_0_is_join_t_3",
        "wall3_0_is_join_t270",
        "wall3_0_is_join_t180",
        "wall3_0_is_join_t90",
        "wall3_0_is_join_t",
        "wall3_0_is_join_t270_2",
        "wall3_0_is_join_t180_2",
        "wall3_0_is_join_t90_2",
        "wall3_0_is_join_t_2",
        "wall3_0_is_join_t270_1",
        "wall3_0_is_join_t180_1",
        "wall3_0_is_join_t90_1",
        "wall3_0_is_join_t_1",
        // --------------------------------------------------------------------
        "wall3_0_is_join_x",
        "wall3_0_is_join_x1",
        "wall3_0_is_join_x1_270",
        "wall3_0_is_join_x1_180",
        "wall3_0_is_join_x1_90",
        "wall3_0_is_join_x2",
        "wall3_0_is_join_x2_270",
        "wall3_0_is_join_x2_180",
        "wall3_0_is_join_x2_90",
        "wall3_0_is_join_x3",
        "wall3_0_is_join_x3_180",
        "wall3_0_is_join_x4",
        "wall3_0_is_join_x4_270",
        "wall3_0_is_join_x4_180",
        "wall3_0_is_join_x4_90",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "wall4_0_0",
        "wall4_0_is_join_node",
        "wall4_0_is_join_left",
        "wall4_0_is_join_bot",
        "wall4_0_is_join_right",
        "wall4_0_is_join_top",
        "wall4_0_is_join_horiz",
        "wall4_0_is_join_vert",
        "wall4_0_is_join_tl2",
        "wall4_0_is_join_bl2",
        "wall4_0_is_join_br2",
        "wall4_0_is_join_tr2",
        "wall4_0_is_join_tl",
        "wall4_0_is_join_bl",
        "wall4_0_is_join_br",
        "wall4_0_is_join_tr",
        "wall4_0_is_join_t270_3",
        "wall4_0_is_join_t180_3",
        "wall4_0_is_join_t90_3",
        "wall4_0_is_join_t_3",
        "wall4_0_is_join_t270",
        "wall4_0_is_join_t180",
        "wall4_0_is_join_t90",
        "wall4_0_is_join_t",
        "wall4_0_is_join_t270_2",
        "wall4_0_is_join_t180_2",
        "wall4_0_is_join_t90_2",
        "wall4_0_is_join_t_2",
        "wall4_0_is_join_t270_1",
        "wall4_0_is_join_t180_1",
        "wall4_0_is_join_t90_1",
        "wall4_0_is_join_t_1",
        // --------------------------------------------------------------------
        "wall4_0_is_join_x",
        "wall4_0_is_join_x1",
        "wall4_0_is_join_x1_270",
        "wall4_0_is_join_x1_180",
        "wall4_0_is_join_x1_90",
        "wall4_0_is_join_x2",
        "wall4_0_is_join_x2_270",
        "wall4_0_is_join_x2_180",
        "wall4_0_is_join_x2_90",
        "wall4_0_is_join_x3",
        "wall4_0_is_join_x3_180",
        "wall4_0_is_join_x4",
        "wall4_0_is_join_x4_270",
        "wall4_0_is_join_x4_180",
        "wall4_0_is_join_x4_90",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "wall5_0_0",
        "wall5_0_is_join_node",
        "wall5_0_is_join_left",
        "wall5_0_is_join_bot",
        "wall5_0_is_join_right",
        "wall5_0_is_join_top",
        "wall5_0_is_join_horiz",
        "wall5_0_is_join_vert",
        "wall5_0_is_join_tl2",
        "wall5_0_is_join_bl2",
        "wall5_0_is_join_br2",
        "wall5_0_is_join_tr2",
        "wall5_0_is_join_tl",
        "wall5_0_is_join_bl",
        "wall5_0_is_join_br",
        "wall5_0_is_join_tr",
        "wall5_0_is_join_t270_3",
        "wall5_0_is_join_t180_3",
        "wall5_0_is_join_t90_3",
        "wall5_0_is_join_t_3",
        "wall5_0_is_join_t270",
        "wall5_0_is_join_t180",
        "wall5_0_is_join_t90",
        "wall5_0_is_join_t",
        "wall5_0_is_join_t270_2",
        "wall5_0_is_join_t180_2",
        "wall5_0_is_join_t90_2",
        "wall5_0_is_join_t_2",
        "wall5_0_is_join_t270_1",
        "wall5_0_is_join_t180_1",
        "wall5_0_is_join_t90_1",
        "wall5_0_is_join_t_1",
        // --------------------------------------------------------------------
        "wall5_0_is_join_x",
        "wall5_0_is_join_x1",
        "wall5_0_is_join_x1_270",
        "wall5_0_is_join_x1_180",
        "wall5_0_is_join_x1_90",
        "wall5_0_is_join_x2",
        "wall5_0_is_join_x2_270",
        "wall5_0_is_join_x2_180",
        "wall5_0_is_join_x2_90",
        "wall5_0_is_join_x3",
        "wall5_0_is_join_x3_180",
        "wall5_0_is_join_x4",
        "wall5_0_is_join_x4_270",
        "wall5_0_is_join_x4_180",
        "wall5_0_is_join_x4_90",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "wall6_0_0",
        "wall6_0_is_join_node",
        "wall6_0_is_join_left",
        "wall6_0_is_join_bot",
        "wall6_0_is_join_right",
        "wall6_0_is_join_top",
        "wall6_0_is_join_horiz",
        "wall6_0_is_join_vert",
        "wall6_0_is_join_tl2",
        "wall6_0_is_join_bl2",
        "wall6_0_is_join_br2",
        "wall6_0_is_join_tr2",
        "wall6_0_is_join_tl",
        "wall6_0_is_join_bl",
        "wall6_0_is_join_br",
        "wall6_0_is_join_tr",
        "wall6_0_is_join_t270_3",
        "wall6_0_is_join_t180_3",
        "wall6_0_is_join_t90_3",
        "wall6_0_is_join_t_3",
        "wall6_0_is_join_t270",
        "wall6_0_is_join_t180",
        "wall6_0_is_join_t90",
        "wall6_0_is_join_t",
        "wall6_0_is_join_t270_2",
        "wall6_0_is_join_t180_2",
        "wall6_0_is_join_t90_2",
        "wall6_0_is_join_t_2",
        "wall6_0_is_join_t270_1",
        "wall6_0_is_join_t180_1",
        "wall6_0_is_join_t90_1",
        "wall6_0_is_join_t_1",
        // --------------------------------------------------------------------
        "wall6_0_is_join_x",
        "wall6_0_is_join_x1",
        "wall6_0_is_join_x1_270",
        "wall6_0_is_join_x1_180",
        "wall6_0_is_join_x1_90",
        "wall6_0_is_join_x2",
        "wall6_0_is_join_x2_270",
        "wall6_0_is_join_x2_180",
        "wall6_0_is_join_x2_90",
        "wall6_0_is_join_x3",
        "wall6_0_is_join_x3_180",
        "wall6_0_is_join_x4",
        "wall6_0_is_join_x4_270",
        "wall6_0_is_join_x4_180",
        "wall6_0_is_join_x4_90",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "fireball1a-tr",
        "fireball1a-right",
        "fireball1a-br",
        "fireball1a-down",
        "fireball1a-bl",
        "fireball1a-left",
        "fireball1a-tl",
        "fireball1a-up",
        "fireball1b-tr",
        "fireball1b-right",
        "fireball1b-br",
        "fireball1b-down",
        "fireball1b-bl",
        "fireball1b-left",
        "fireball1b-tl",
        "fireball1b-up",
        "fireball1c-tr",
        "fireball1c-right",
        "fireball1c-br",
        "fireball1c-down",
        "fireball1c-bl",
        "fireball1c-left",
        "fireball1c-tl",
        "fireball1c-up",
        "fireball1d-tr",
        "fireball1d-right",
        "fireball1d-br",
        "fireball1d-down",
        "fireball1d-bl",
        "fireball1d-left",
        "fireball1d-tl",
        "fireball1d-up",

        // --------------------------------------------------------------------
        
        "ghost1a-right",
        "ghost1a-br",
        "ghost1a-down",
        "ghost1a-bl",
        "ghost1a-left",
        "ghost1a-tl",
        "ghost1a-up",
        "ghost1a-tr",

        "ghost1b-right",
        "ghost1b-br",
        "ghost1b-down",
        "ghost1b-bl",
        "ghost1b-left",
        "ghost1b-tl",
        "ghost1b-up",
        "ghost1b-tr",

        "ghost1c-right",
        "ghost1c-br",
        "ghost1c-down",
        "ghost1c-bl",
        "ghost1c-left",
        "ghost1c-tl",
        "ghost1c-up",
        "ghost1c-tr",

        "ghost1d-right",
        "ghost1d-br",
        "ghost1d-down",
        "ghost1d-bl",
        "ghost1d-left",
        "ghost1d-tl",
        "ghost1d-up",
        "ghost1d-tr",

        // --------------------------------------------------------------------
        
        "ghost2a-right",
        "ghost2a-br",
        "ghost2a-down",
        "ghost2a-bl",
        "ghost2a-left",
        "ghost2a-tl",
        "ghost2a-up",
        "ghost2a-tr",

        "ghost2b-right",
        "ghost2b-br",
        "ghost2b-down",
        "ghost2b-bl",
        "ghost2b-left",
        "ghost2b-tl",
        "ghost2b-up",
        "ghost2b-tr",

        "ghost2c-right",
        "ghost2c-br",
        "ghost2c-down",
        "ghost2c-bl",
        "ghost2c-left",
        "ghost2c-tl",
        "ghost2c-up",
        "ghost2c-tr",

        "ghost2d-right",
        "ghost2d-br",
        "ghost2d-down",
        "ghost2d-bl",
        "ghost2d-left",
        "ghost2d-tl",
        "ghost2d-up",
        "ghost2d-tr",

        // --------------------------------------------------------------------
        "ghost3a-right",
        "ghost3a-br",
        "ghost3a-down",
        "ghost3a-bl",
        "ghost3a-left",
        "ghost3a-tl",
        "ghost3a-up",
        "ghost3a-tr",

        "ghost3b-right",
        "ghost3b-br",
        "ghost3b-down",
        "ghost3b-bl",
        "ghost3b-left",
        "ghost3b-tl",
        "ghost3b-up",
        "ghost3b-tr",

        "ghost3c-right",
        "ghost3c-br",
        "ghost3c-down",
        "ghost3c-bl",
        "ghost3c-left",
        "ghost3c-tl",
        "ghost3c-up",
        "ghost3c-tr",

        "ghost3d-right",
        "ghost3d-br",
        "ghost3d-down",
        "ghost3d-bl",
        "ghost3d-left",
        "ghost3d-tl",
        "ghost3d-up",
        "ghost3d-tr",

        // --------------------------------------------------------------------
        "monk1-demo-right",
        "monk1-demo-br",
        "monk1-demo-down",
        "monk1-demo-bl",
        "monk1-demo-left",
        "monk1-demo-tl",
        "monk1-demo-up",
        "monk1-demo-tr",
        "skull",
        "eyes",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "demon1-demo-right",
        "demon1-demo-br",
        "demon1-demo-down",
        "demon1-demo-bl",
        "demon1-demo-left",
        "demon1-demo-tl",
        "demon1-demo-up",
        "demon1-demo-tr",
        "demon1-right",
        "demon1-br",
        "demon1-down",
        "demon1-bl",
        "demon1-left",
        "demon1-tl",
        "demon1-up",
        "demon1-tr",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "lizard1-demo-right",
        "lizard1-demo-br",
        "lizard1-demo-down",
        "lizard1-demo-bl",
        "lizard1-demo-left",
        "lizard1-demo-tl",
        "lizard1-demo-up",
        "lizard1-demo-tr",
        "lizard1-right",
        "lizard1-br",
        "lizard1-down",
        "lizard1-bl",
        "lizard1-left",
        "lizard1-tl",
        "lizard1-up",
        "lizard1-tr",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "warrior-demo-right",
        "warrior-demo-br",
        "warrior-demo-down",
        "warrior-demo-bl",
        "warrior-demo-left",
        "warrior-demo-tl",
        "warrior-demo-up",
        "warrior-demo-tr",
        "warrior-right",
        "warrior-br",
        "warrior-down",
        "warrior-bl",
        "warrior-left",
        "warrior-tl",
        "warrior-up",
        "warrior-tr",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "valkyrie-demo-right",
        "valkyrie-demo-br",
        "valkyrie-demo-down",
        "valkyrie-demo-bl",
        "valkyrie-demo-left",
        "valkyrie-demo-tl",
        "valkyrie-demo-up",
        "valkyrie-demo-tr",
        "valkyrie-right",
        "valkyrie-br",
        "valkyrie-down",
        "valkyrie-bl",
        "valkyrie-left",
        "valkyrie-tl",
        "valkyrie-up",
        "valkyrie-tr",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "death1-demo-right",
        "death1-demo-br",
        "death1-demo-down",
        "death1-demo-bl",
        "death1-demo-left",
        "death1-demo-tl",
        "death1-demo-up",
        "death1-demo-tr",
        "death1-right",
        "death1-br",
        "death1-down",
        "death1-bl",
        "death1-left",
        "death1-tl",
        "death1-up",
        "death1-tr",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "wizard-demo-right",
        "wizard-demo-br",
        "wizard-demo-down",
        "wizard-demo-bl",
        "wizard-demo-left",
        "wizard-demo-tl",
        "wizard-demo-up",
        "wizard-demo-tr",
        "wizard-right",
        "wizard-br",
        "wizard-down",
        "wizard-bl",
        "wizard-left",
        "wizard-tl",
        "wizard-up",
        "wizard-tr",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "elf-demo-right",
        "elf-demo-br",
        "elf-demo-down",
        "elf-demo-bl",
        "elf-demo-left",
        "elf-demo-tl",
        "elf-demo-up",
        "elf-demo-tr",
        "elf-right",
        "elf-br",
        "elf-down",
        "elf-bl",
        "elf-left",
        "elf-tl",
        "elf-up",
        "elf-tr",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "dwarf-demo-right",
        "dwarf-demo-br",
        "dwarf-demo-down",
        "dwarf-demo-bl",
        "dwarf-demo-left",
        "dwarf-demo-tl",
        "dwarf-demo-up",
        "dwarf-demo-tr",
        "dwarf-right",
        "dwarf-br",
        "dwarf-down",
        "dwarf-bl",
        "dwarf-left",
        "dwarf-tl",
        "dwarf-up",
        "dwarf-tr",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "magic1.1",
        "magic2.1",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "sparks1.1",
        "sparks2.1",
        "sparks3.1",
        0,
        0,
        0,
        // --------------------------------------------------------------------
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "magic1.2",
        "magic2.2",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "sparks1.2",
        "sparks2.2",
        "sparks3.2",
        0,
        0,
        0,
        // --------------------------------------------------------------------
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "magic1.3",
        "magic2.3",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "sparks1.3",
        "sparks2.3",
        "sparks3.3",
        0,
        0,
        0,
        // --------------------------------------------------------------------
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "magic1.4",
        "magic2.4",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "sparks1.4",
        "sparks2.4",
        "sparks3.4",
        0,
        0,
        0,
        // --------------------------------------------------------------------
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "magic1.5",
        "magic2.5",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "sparks1.5",
        "sparks2.5",
        "sparks3.5",
        0,
        0,
        0,
        // --------------------------------------------------------------------
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "magic1.6",
        "magic2.6",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "sparks1.6",
        "sparks2.6",
        "sparks3.6",
        0,
        0,
        0,
        // --------------------------------------------------------------------
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "magic1.7",
        "magic2.7",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "sparks1.7",
        "sparks2.7",
        "sparks3.7",
        0,
        0,
        0,
        // --------------------------------------------------------------------
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "sword3.1",
        "sword3.2",
        "sword3.3",
        "sword3.4",
        "sword3.5",
        "sword3.6",
        "sword3.7",
        "sword3.8",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "sword2.1",
        "sword2.2",
        "sword2.3",
        "sword2.4",
        "sword2.5",
        "sword2.6",
        "sword2.7",
        "sword2.8",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "sword1.1",
        "sword1.2",
        "sword1.3",
        "sword1.4",
        "sword1.5",
        "sword1.6",
        "sword1.7",
        "sword1.8",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "scythe1.1",
        "scythe1.2",
        "scythe1.3",
        "scythe1.4",
        "scythe1.5",
        "scythe1.6",
        "scythe1.7",
        "scythe1.8",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "wand1.1",
        "wand1.2",
        "wand1.3",
        "wand1.4",
        "wand1.5",
        "wand1.6",
        "wand1.7",
        "wand1.8",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "bow1.1",
        "bow1.2",
        "bow1.3",
        "bow1.4",
        "bow1.5",
        "bow1.6",
        "bow1.7",
        "bow1.8",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "axe2.1",
        "axe2.2",
        "axe2.3",
        "axe2.4",
        "axe2.5",
        "axe2.6",
        "axe2.7",
        "axe2.8",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "axe1.1",
        "axe1.2",
        "axe1.3",
        "axe1.4",
        "axe1.5",
        "axe1.6",
        "axe1.7",
        "axe1.8",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "weapon_swing1.12",
        "weapon_swing1.11",
        "weapon_swing1.10",
        "weapon_swing1.9",
        "weapon_swing1.8",
        "weapon_swing1.7",
        "weapon_swing1.6",
        "weapon_swing1.5",
        "weapon_swing1.4",
        "weapon_swing1.3",
        "weapon_swing1.2",
        "weapon_swing1.1",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "weapon_swing2.1",
        "weapon_swing2.2",
        "weapon_swing2.3",
        "weapon_swing2.4",
        "weapon_swing2.5",
        "weapon_swing2.6",
        "weapon_swing2.7",
        "weapon_swing2.8",
        "weapon_swing2.9",
        "weapon_swing2.10",
        "weapon_swing2.11",
        "weapon_swing2.12",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "weapon_swing3.1",
        "weapon_swing3.2",
        "weapon_swing3.3",
        "weapon_swing3.4",
        "weapon_swing3.5",
        "weapon_swing3.6",
        "weapon_swing3.7",
        "weapon_swing3.8",
        "weapon_swing3.9",
        "weapon_swing3.10",
        "weapon_swing3.11",
        "weapon_swing3.12",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        // --------------------------------------------------------------------
        "weapon_swing4.12",
        "weapon_swing4.11",
        "weapon_swing4.10",
        "weapon_swing4.9",
        "weapon_swing4.8",
        "weapon_swing4.7",
        "weapon_swing4.6",
        "weapon_swing4.5",
        "weapon_swing4.4",
        "weapon_swing4.3",
        "weapon_swing4.2",
        "weapon_swing4.1",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    };

    tile_load_arr("sprites_small", TILE_WIDTH, TILE_HEIGHT,
                  ARRAY_SIZE(small_tiles), small_tiles);

    static const char *explosion_tiles[] = {
        // --------------------------------------------------------------------
        "explosion1.1",
        "explosion1.2",
        "explosion1.3",
        "explosion1.4",
        "explosion2.1",
        "explosion2.2",
        "explosion2.3",
        "explosion2.4",
        // --------------------------------------------------------------------
        "explosion1.5",
        "explosion1.6",
        "explosion1.7",
        "explosion1.8",
        "explosion2.5",
        "explosion2.6",
        "explosion2.7",
        "explosion2.8",
        // --------------------------------------------------------------------
        "explosion1.9",
        "explosion1.10",
        "explosion1.11",
        "explosion1.12",
        "explosion2.9",
        "explosion2.10",
        "explosion2.11",
        "explosion2.12",
        // --------------------------------------------------------------------
        "explosion1.13",
        "explosion1.14",
        "explosion1.15",
        "explosion1.16",
        "explosion2.13",
        "explosion2.14",
        "explosion2.15",
        "explosion2.16",
        // --------------------------------------------------------------------
        "explosion3.1",
        "explosion3.2",
        "explosion3.3",
        "explosion3.4",
        "explosion4.1",
        "explosion4.2",
        "explosion4.3",
        "explosion4.4",
        // --------------------------------------------------------------------
        "explosion3.5",
        "explosion3.6",
        "explosion3.7",
        "explosion3.8",
        "explosion4.5",
        "explosion4.6",
        "explosion4.7",
        "explosion4.8",
        // --------------------------------------------------------------------
        "explosion3.9",
        "explosion3.10",
        "explosion3.11",
        "explosion3.12",
        "explosion4.9",
        "explosion4.10",
        "explosion4.11",
        "explosion4.12",
        // --------------------------------------------------------------------
        "explosion3.13",
        "explosion3.14",
        "explosion3.15",
        "explosion3.16",
        "explosion4.13",
        "explosion4.14",
        "explosion4.15",
        "explosion4.16",
    };

    tile_load_arr("explosion", 128, 128,
                  ARRAY_SIZE(explosion_tiles), explosion_tiles);

    static const char *cloudkill_tiles[] = {
        // --------------------------------------------------------------------
        "cloudkill1.1",
        "cloudkill1.2",
        "cloudkill1.3",
        "cloudkill1.4",
        "cloudkill2.1",
        "cloudkill2.2",
        "cloudkill2.3",
        "cloudkill2.4",
        // --------------------------------------------------------------------
        "cloudkill1.5",
        "cloudkill1.6",
        "cloudkill1.7",
        "cloudkill1.8",
        "cloudkill2.5",
        "cloudkill2.6",
        "cloudkill2.7",
        "cloudkill2.8",
        // --------------------------------------------------------------------
        "cloudkill1.9",
        "cloudkill1.10",
        "cloudkill1.11",
        "cloudkill1.12",
        "cloudkill2.9",
        "cloudkill2.10",
        "cloudkill2.11",
        "cloudkill2.12",
        // --------------------------------------------------------------------
        "cloudkill1.13",
        "cloudkill1.14",
        "cloudkill1.15",
        "cloudkill1.16",
        "cloudkill2.13",
        "cloudkill2.14",
        "cloudkill2.15",
        "cloudkill2.16",
        // --------------------------------------------------------------------
        "cloudkill3.1",
        "cloudkill3.2",
        "cloudkill3.3",
        "cloudkill3.4",
        "cloudkill4.1",
        "cloudkill4.2",
        "cloudkill4.3",
        "cloudkill4.4",
        // --------------------------------------------------------------------
        "cloudkill3.5",
        "cloudkill3.6",
        "cloudkill3.7",
        "cloudkill3.8",
        "cloudkill4.5",
        "cloudkill4.6",
        "cloudkill4.7",
        "cloudkill4.8",
        // --------------------------------------------------------------------
        "cloudkill3.9",
        "cloudkill3.10",
        "cloudkill3.11",
        "cloudkill3.12",
        "cloudkill4.9",
        "cloudkill4.10",
        "cloudkill4.11",
        "cloudkill4.12",
        // --------------------------------------------------------------------
        "cloudkill3.13",
        "cloudkill3.14",
        "cloudkill3.15",
        "cloudkill3.16",
        "cloudkill4.13",
        "cloudkill4.14",
        "cloudkill4.15",
        "cloudkill4.16",
    };

    tile_load_arr("cloudkill", 128, 128,
                  ARRAY_SIZE(cloudkill_tiles), cloudkill_tiles);

    static const char *poison_tiles[] = {
        // --------------------------------------------------------------------
        "poison1.1",
        "poison1.2",
        "poison1.3",
        "poison1.4",
        "poison2.1",
        "poison2.2",
        "poison2.3",
        "poison2.4",
        // --------------------------------------------------------------------
        "poison1.5",
        "poison1.6",
        "poison1.7",
        "poison1.8",
        "poison2.5",
        "poison2.6",
        "poison2.7",
        "poison2.8",
        // --------------------------------------------------------------------
        "poison1.9",
        "poison1.10",
        "poison1.11",
        "poison1.12",
        "poison2.9",
        "poison2.10",
        "poison2.11",
        "poison2.12",
        // --------------------------------------------------------------------
        "poison1.13",
        "poison1.14",
        "poison1.15",
        "poison1.16",
        "poison2.13",
        "poison2.14",
        "poison2.15",
        "poison2.16",
        // --------------------------------------------------------------------
        "poison3.1",
        "poison3.2",
        "poison3.3",
        "poison3.4",
        "poison4.1",
        "poison4.2",
        "poison4.3",
        "poison4.4",
        // --------------------------------------------------------------------
        "poison3.5",
        "poison3.6",
        "poison3.7",
        "poison3.8",
        "poison4.5",
        "poison4.6",
        "poison4.7",
        "poison4.8",
        // --------------------------------------------------------------------
        "poison3.9",
        "poison3.10",
        "poison3.11",
        "poison3.12",
        "poison4.9",
        "poison4.10",
        "poison4.11",
        "poison4.12",
        // --------------------------------------------------------------------
        "poison3.13",
        "poison3.14",
        "poison3.15",
        "poison3.16",
        "poison4.13",
        "poison4.14",
        "poison4.15",
        "poison4.16",
    };

    tile_load_arr("poison", 128, 128,
                  ARRAY_SIZE(poison_tiles), poison_tiles);

    /*
     * Walls
     */
    thing_template_load(&THING_WALL1, "data/things/wall1");
    thing_template_load(&THING_ROCK1, "data/things/rock1");
    thing_template_load(&THING_WALL2, "data/things/wall2");
    thing_template_load(&THING_WALL3, "data/things/wall3");
    thing_template_load(&THING_WALL4, "data/things/wall4");
    thing_template_load(&THING_WALL5, "data/things/wall5");
    thing_template_load(&THING_WALL6, "data/things/wall6");
    thing_template_load(&THING_FLOOR1, "data/things/floor1");
    thing_template_load(&THING_FLOOR2, "data/things/floor2");
    thing_template_load(&THING_FLOOR3, "data/things/floor3");
    thing_template_load(&THING_FLOOR4, "data/things/floor4");
    thing_template_load(&THING_FLOOR5, "data/things/floor5");
    thing_template_load(&THING_FLOOR6, "data/things/floor6");
    thing_template_load(&THING_DOOR1, "data/things/door1");
    thing_template_load(&THING_DOOR2, "data/things/door2");
    thing_template_load(&THING_NOENTRY, "data/things/noentry");
    thing_template_load(&THING_PIPE, "data/things/pipe");
    thing_template_load(&THING_BRAZIER, "data/things/brazier");
    thing_template_load(&THING_EXIT1, "data/things/exit1");
    thing_template_load(&THING_EXIT2, "data/things/exit2");
    thing_template_load(&THING_EXIT3, "data/things/exit3");
    thing_template_load(&THING_EXIT4, "data/things/exit4");
    thing_template_load(&THING_EXIT5, "data/things/exit5");
    thing_template_load(&THING_EXIT6, "data/things/exit6");
    thing_template_load(&THING_EXIT7, "data/things/exit7");
    thing_template_load(&THING_GENERATOR1, "data/things/generator1");
    thing_template_load(&THING_BONEPILE1, "data/things/bonepile1");
    thing_template_load(&THING_BONEPILE2, "data/things/bonepile2");
    thing_template_load(&THING_BONEPILE3, "data/things/bonepile3");
    thing_template_load(&THING_GENERATOR5, "data/things/generator5");
    thing_template_load(&THING_GENERATOR6, "data/things/generator6");
    thing_template_load(&THING_GENERATOR7, "data/things/generator7");

    /*
     * Projectiles
     */
    thing_template_load(&THING_ARROW, "data/things/arrow");
    thing_template_load(&THING_FIREBALL, "data/things/fireball");

    /*
     * Explosions
     */
    thing_template_load(&THING_WEAPON_HIT1, "data/things/weapon_swing1");

    thing_template_load(&THING_EXPLOSION1, "data/things/explosion1");
    thing_template_load(&THING_EXPLOSION2, "data/things/explosion2");
    thing_template_load(&THING_EXPLOSION3, "data/things/explosion3");
    thing_template_load(&THING_EXPLOSION4, "data/things/explosion4");

    thing_template_load(&THING_POISON1, "data/things/poison1");
    thing_template_load(&THING_POISON2, "data/things/poison2");
    thing_template_load(&THING_POISON3, "data/things/poison3");
    thing_template_load(&THING_POISON4, "data/things/poison4");

    thing_template_load(&THING_CLOUDKILL1, "data/things/cloudkill1");
    thing_template_load(&THING_CLOUDKILL2, "data/things/cloudkill2");
    thing_template_load(&THING_CLOUDKILL3, "data/things/cloudkill3");
    thing_template_load(&THING_CLOUDKILL4, "data/things/cloudkill4");

    thing_template_load(&THING_SPARKS1, "data/things/sparks1");
    thing_template_load(&THING_SPARKS2, "data/things/sparks2");
    thing_template_load(&THING_SPARKS3, "data/things/sparks3");

    /*
     * Important stuff that cannot be used by clicking on.
     */
    thing_template_load(&THING_KEY, "data/things/key");
    thing_template_load(&THING_KEYS2, "data/things/keys2");
    thing_template_load(&THING_KEYS3, "data/things/keys3");

    /*
     * Wearable items that are used as weapons. Shown first on list of player 
     * items.
     */
    thing_template_load(&THING_WAND_FIRE, "data/things/wand_fire");
    thing_template_load(&THING_SWORD1, "data/things/sword1");
    thing_template_load(&THING_SWORD2, "data/things/sword2");
    thing_template_load(&THING_SWORD3, "data/things/sword3");
    thing_template_load(&THING_AXE1, "data/things/axe1");
    thing_template_load(&THING_AXE2, "data/things/axe2");
    thing_template_load(&THING_SCYTHE1, "data/things/scythe1");
    thing_template_load(&THING_BOW1, "data/things/bow1");
    thing_template_load(&THING_BOW2, "data/things/bow2");
    thing_template_load(&THING_BOW3, "data/things/bow3");
    thing_template_load(&THING_BOW4, "data/things/bow4");
    thing_template_load(&THING_AMULET1, "data/things/amulet1");

    /*
     * Lesser items like food.
     */
    thing_template_load(&THING_APPLE, 
                        "data/things/apple");
    thing_template_load(&THING_APPLE_POISON, 
                        "data/things/apple_poison");
    thing_template_load(&THING_BREAD, 
                        "data/things/bread");
    thing_template_load(&THING_CHEESE, 
                        "data/things/cheese");
    thing_template_load(&THING_BANANA, 
                        "data/things/banana");

    thing_template_load(&THING_POTION_MONSTICIDE, 
                        "data/things/potion_monsticide");
    thing_template_load(&THING_POTION_FIRE, 
                        "data/things/potion_fire");
    thing_template_load(&THING_POTION_CLOUDKILL, 
                        "data/things/potion_cloudkill");
    thing_template_load(&THING_POTION_LIFE, 
                        "data/things/potion_life");
    thing_template_load(&THING_POTION_SHIELD, 
                        "data/things/potion_shield");
    thing_template_load(&THING_WATER, 
                        "data/things/water");
    thing_template_load(&THING_WATER_POISON, 
                        "data/things/water_poison");

    /*
     * Lowest priority junk
     */
    thing_template_load(&THING_MASK1, "data/things/ring1");
    thing_template_load(&THING_RING2, "data/things/ring2");
    thing_template_load(&THING_RING3, "data/things/ring3");
    thing_template_load(&THING_GEM1, "data/things/gem1");
    thing_template_load(&THING_GEM2, "data/things/gem2");
    thing_template_load(&THING_GEM3, "data/things/gem3");
    thing_template_load(&THING_GEM4, "data/things/gem4");
    thing_template_load(&THING_GEM5, "data/things/gem5");
    thing_template_load(&THING_GEM6, "data/things/gem6");
    thing_template_load(&THING_GEM7, "data/things/gem7");
    thing_template_load(&THING_COINS1, "data/things/coins1");
    thing_template_load(&THING_CHEST1, "data/things/chest1");
    thing_template_load(&THING_SPAM, "data/things/spam");

    /*
     * Heroes. Must come after items they can carry.
     */
    thing_template_load(&THING_WARRIOR, "data/things/warrior");
    thing_template_load(&THING_VALKYRIE, "data/things/valkyrie");
    thing_template_load(&THING_WIZARD, "data/things/wizard");
    thing_template_load(&THING_ELF, "data/things/elf");
    thing_template_load(&THING_DWARF, "data/things/dwarf");

    /*
     * Monsters
     */
    thing_template_load(&THING_GHOST1, "data/things/ghost1");
    thing_template_load(&THING_GHOST2, "data/things/ghost2");
    thing_template_load(&THING_GHOST3, "data/things/ghost3");
    thing_template_load(&THING_DEMON, "data/things/demon");
    thing_template_load(&THING_MONK, "data/things/monk");
    thing_template_load(&THING_LIZARD, "data/things/lizard");
    thing_template_load(&THING_DEATH, "data/things/death");
    thing_template_load(&THING_PLANT, "data/things/plant");
    thing_template_load(&THING_SEEDPOD, "data/things/seedpod");

    /*
     * Weapon animations.
     */
    thing_template_load(&THING_WAND1_ANIM, "data/things/wand1_anim");
    thing_template_load(&THING_SWORD1_ANIM, "data/things/sword1_anim");
    thing_template_load(&THING_SWORD2_ANIM, "data/things/sword2_anim");
    thing_template_load(&THING_SWORD3_ANIM, "data/things/sword3_anim");
    thing_template_load(&THING_AXE1_ANIM, "data/things/axe1_anim");
    thing_template_load(&THING_AXE2_ANIM, "data/things/axe2_anim");
    thing_template_load(&THING_BOW1_ANIM, "data/things/bow1_anim");
    thing_template_load(&THING_SCYTHE1_ANIM, "data/things/scythe1_anim");

    return (true);
}

uint8_t resource_init (void)
{
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_1,
                          0, "resource_init_1");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_2,
                          0, "resource_init_2");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_3,
                          0, "resource_init_3");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_4,
                          0, "resource_init_4");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_5,
                          0, "resource_init_5");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_6,
                          0, "resource_init_6");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_7,
                          0, "resource_init_7");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_8,
                          0, "resource_init_8");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_9,
                          0, "resource_init_9");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_10,
                          0, "resource_init_10");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_11,
                          0, "resource_init_11");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_12,
                          0, "resource_init_12");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_13,
                          0, "resource_init_13");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_14,
                          0, "resource_init_14");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_15,
                          0, "resource_init_15");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_16,
                          0, "resource_init_16");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_17,
                          0, "resource_init_17");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_18,
                          0, "resource_init_18");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_19,
                          0, "resource_init_19");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_20,
                          0, "resource_init_20");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_21,
                          0, "resource_init_21");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_22,
                          0, "resource_init_22");
    action_init_fn_create(&init_fns,
                          (action_init_fn_callback)resource_init_23,
                          0, "resource_init_23");

    return (true);
}
